gabime/spdlog

include/spdlog/details/format.cc
include/spdlog/details/os.h

Previously, you would get a warning if WIN32_LEAN_AND_MEAN was already defined before including spdlog. This pull request fixes that.

Fixed 2 macro redefinition warnings related to WIN32_LEAN_AND_MEAN.

---

include/spdlog/async_logger.h
include/spdlog/details/async_log_helper.h
include/spdlog/details/async_logger_impl.h
include/spdlog/details/registry.h
include/spdlog/details/spdlog_impl.h
include/spdlog/spdlog.h

for me it's much better to lose few lines of log vs stopping the processing thread due to buffer overflow.
maybe set_async_mode is somewhat over complicated now, feel free to suggest better design.
thx a lot

discard policies on queue overflow

---

bench/Makefile
bench/Makefile.mingw
example/Makefile
example/Makefile.clang
example/Makefile.mingw

What if, for example, my clang compiler executable name is not clang but clang-3.5?

respect user-set compiler name

---

include/spdlog/common.h
include/spdlog/details/line_logger.h
include/spdlog/details/pattern_formatter_impl.h

There are two changes here - short (one letter) level name which is to me important (less space / more efficient / better readability due to constant prefix length).
And another is performance optimization - if SPDLOG_CLOCK_COARSE is defined than COARSE clock is used. Which makes HUGE impact.
W/o COARSE (normal logging)
`[denis@centosvm example]$ ./bench 
*******************************************************************************
Single thread, 1,048,576 iterations, auto flush=0
*******************************************************************************
rotating_st...		895,865/sec
daily_st...		790,050/sec
null_st...		2,152,852/sec
*******************************************************************************
10 threads sharing same logger, 1,048,576 iterations, auto_flush=0 …

coarse clock, short log level

---

.travis.yml
README.md
example/Makefile
install_libcxx.sh

- add travis-ci automated testing
- only for the examples
- compiles with clang-3.5, 3.6, 3.7 (using libc++), and gcc 4.9 (using libstdc++)
- with and without address sanitizer
- in c++11 and c++14 `-std=` modes
- runs example and bench with and without valgrind
Note: the only thing one can get right now from this is that the code compiles successfully. 
To check that is doing the right thing one would need to add unit/regression tests.

travis-ci automated testing

---

include/spdlog/details/line_logger.h

Custom stream operators for line_logger need to be able to check line_logger.enabled and skip execution if it's false.

Expose line_logger enabled state for custom types in stream operators

---

CMakeLists.txt
cmake/Config.cmake.in
example/CMakeLists.txt

With this CMake code library can be installed and found by `find_package` like this:
```cmake
find_package(spdlog CONFIG REQUIRED)
add_executable(example example.cpp)
target_link_libraries(example spdlog::spdlog)
```
also tests can be run using CTest.
I see no releases so version set to `1.0.0`.

Add CMake build

---

include/spdlog/sinks/dist_sink.h

Setting up dist_sink to a logger will inject a layer between the logger and
(some of) it's sinks. Sinks can be added and removed to dist_sink dynamically.

Add distributional sink

---

include/spdlog/details/os.h

In Linux (Ubuntu 15.10) version of MinGW-w64 "windows.h" is named with small letter first. As Linux uses case-sensitive FS by default, the compiler could not find it under the name "Windows.h".

Renamed "Windows.h" to "windows.h" for building spdlog on MinGW using case-sensitive file system.

---

include/spdlog/details/os.h

The API GetDynamicTimeZoneInformation is supported from Windows Server 2008. Thus, projects use spdlog cannot be compiled for prevous servers. This branch fixes this problem by replacing GetDynamicTimeZoneInformation with GetTimeZoneInformation in this case.

Replace GetDynamicTimeZoneInformation to GetTimeZoneInformation.

---

bench/Makefile
bench/run_all.sh
bench/zf_log-bench-mt.cpp
bench/zf_log-bench.cpp

Adding [zf_log](https://github.com/wonder-mice/zf_log) to performance tests. On my machine (MacBook Pro 2.8GHz Core i7) I'm getting following results (real time, best of 3):
```
1 thread   10 threads   100 threads
zf_log   0.466s     2.711s       2.608s
spdlog   0.747s     5.121s       5.376s
```

Add zf_log to performance tests

---

include/spdlog/details/async_log_helper.h

no need to write move constructor/assignment operator explicitly.

use default move constructor/assignment for async_log_helper

---

include/spdlog/details/spdlog_impl.h
include/spdlog/sinks/syslog_sink.h
include/spdlog/spdlog.h

Syslog is supported on Mac OS X, so there is no reason disallowing it. https://github.com/gabime/spdlog/issues/177

Allow syslog logger on Mac OS X

---

CMakeLists.txt
example/example.cpp
include/spdlog/sinks/ansicolor_sink.h

An sink decorator that applies ANSI coloring based on log levels.
The `ansicolor_sink` wraps around another sink (e.g., `stderr_sink_st::instance()`) and applies ANSI color codes prior to printing each log message. The colors codes vary based on the log level and can be modified/set using the `setColor()` method.
This works out of the box on Linux and OS X. It should work under Windows if you have `NASI.SYS` loaded; otherwise you'll just see the escape characters in the output stream.
Example usage and the default colors—feel free to modify them—are demonstrated in the modified `example.cpp` file.

ANSI color sink decorator

---

include/spdlog/sinks/stdout_sinks.h
tests/includes.h

The current implementation of stdout sink uses std::cout.write, which is really slow.
Writing to stdout via fwrite can increase performance.
I wrote a simple benchmark to compare performance of fwrite(..., stdout) and std::cout.write. fwrite works  more than 28x faster (90 ms VS 2926 ms) in my configuration (Intel Core i7 2630QM, Windows 10, Visual Studio 2015).
Code of benchmark:
```C++
#include <iostream>
#include <chrono>
int main() {
constexpr int howmany = 1000;
const std::string message("spdlog message #: This is some text for your pleasure\n");
// warm up
for (int i = 0; i < howmany; ++i) {
fwrite(message.c_str(), sizeof(char), message.size(), stdout);
fflush(stdout);
std::cout.write(message.c_str(), message.size());
std::cout.flush();
}
const auto fwrite_start = …
```

Performance improvement of stdout sink 

---

include/spdlog/details/line_logger_impl.h
include/spdlog/details/logger_impl.h
include/spdlog/logger.h

Example usage:
```
auto logger = spd::get("some_async_logger");
logger->flush_on(spd::level::error);
logger->info("won't cause flush");
logger->error("will cause flush");
```
The end result is that messages with a log level of error or above will cause the log to be flushed after each message. This ensure that important events are logged while still maintaining performance for more verbose and less critical messages.
This patch maintains backward compatibility. By default the `flush_on()` value is set to `spd::level::off` so that no messages cause a flush.

Automatically flush log if message level is above certain severity.

---

.gitmodules
CMakeLists.txt
bench/CMakeLists.txt
bench/easylogging-bench-mt.cpp
bench/easylogging-bench.cpp
bench/g3log-async.cpp
bench/zf_log-bench-mt.cpp
bench/zf_log-bench.cpp
example/CMakeLists.txt
include/spdlog/sinks/stdout_sinks.h
tests/CMakeLists.txt
tests/header_dependencies/CMakeLists.txt
tests/header_dependencies/main.c
tests/header_dependencies/main.cpp
vendor/CMakeLists.txt

This pull request does the following:
* Fixes the `example/CMakeLists.txt` file so that cmake will build the example without crashing  You can no longer build the example starting at that directory, however. You must use the top-level `CMakeLists.txt` file.
* Added `SPDLOG_BUILD_TESTS` build option. CMake can now build the tests found in the `tests/` subdirectory. You may also run the tests using `make test`.
* Added a test that automatically compiles each spdlog header in isolation to ensure it isn't missing any dependencies (missing `#include` directives). This test is enabled with the `SPDLOG_BUILD_TESTS` option.
* Added `SPDLOG_BUILD_BENCHMARKS` build option. CMake can now build the benchmarks found in the `bench/` subdirectory. The benchmarks will be run when you run `make test`.
* …

CMake script improvements

---

include/spdlog/async_logger.h
include/spdlog/details/async_log_helper.h
include/spdlog/details/async_logger_impl.h
include/spdlog/details/registry.h
include/spdlog/details/spdlog_impl.h
include/spdlog/spdlog.h

Hello Gabime,
I need to write a customized sink that invokes a JNI callback. As you may know, such calls require that running thread was previously attached to JVM.
This is fine, and I can use warmup callback to attach it.
However, it's also required to detach thread from JVM upon its exit. That's why I'm suggesting adding a new teardown callback that would be invoked before worker thread exit.
Please let me know what you think about this new feature.
Have a good day !

In async mode, teardown callback on worker thread exit

---

include/spdlog/details/os.h

Fix throwing exception if DYNAMIC_TIME_ZONE_INFORMATION fails

---

CMakeLists.txt
include/spdlog/sinks/stdout_sinks.h
tests/CMakeLists.txt
tests/header_dependencies/CMakeLists.txt
tests/header_dependencies/main.c
tests/header_dependencies/main.cpp

* Added `SPDLOG_BUILD_TESTS` build option. CMake can now build the tests found in the `tests/` subdirectory. You may also run the tests using `make test`.
* Added a test that automatically compiles each spdlog header in isolation to ensure it isn't missing any dependencies (missing `#include` directives). This test is enabled with the `SPDLOG_BUILD_TESTS` option.
* Fixed a bug discovered by the new header dependency tests.
**Example usage:**
```
$ git clone --recursive https://github.com/gabime/spdlog.git
$ cd spdlog
$ mkdir build
$ cd build
$ cmake .. -DSPDLOG_BUILD_TESTS=1
$ make test
```

Header tests

---

example/example.cpp
include/spdlog/async_logger.h
include/spdlog/common.h
include/spdlog/details/file_helper.h
include/spdlog/details/line_logger_impl.h
include/spdlog/details/mpmc_bounded_q.h
include/spdlog/details/os.h
include/spdlog/details/pattern_formatter_impl.h
include/spdlog/details/registry.h
include/spdlog/details/spdlog_impl.h
include/spdlog/sinks/android_sink.h
include/spdlog/sinks/file_sinks.h
include/spdlog/spdlog.h

(This PR is a duplicate of PR #230. It just targets the `no-exceptions` branch instead of the `master` branch.)
This PR addresses issue #136 by adding the ability to replace the default error handling (i.e., throwing a `spdlog_ex` exception) with a custom error handler (e.g., one that prints the error to `STDERR`).
* All instances of `throw spdlog_ex` have been replaced with a call to the new `spdlog::error()` function (with one exception—see Further Work below).
* The `spdlog::error()` function takes a `std::string` argument and passes it along to the error handler.
* The default error handler simple throws a `spdlog_ex` exception containing the string as the message.
* The user may provide their own error handler with the following signature: `void my_error_handler(const std::string& …

Allow custom error handling to avoid exceptions

---

include/spdlog/details/os.h

fix some linux-isms for spdlog on freebsd systems
- FreeBSD uses plain-old ``stat`` (not ``stat64``)
- ``errno_str``'s else requires GNU extensions, not available by default
on FreeBSD. The one used by apple systems is most correct

Add FreeBSD compatibility defs

---

.gitignore
example/CMakeLists.txt
example/multisink.cpp
include/spdlog/details/async_log_helper.h
include/spdlog/details/logger_impl.h
include/spdlog/sinks/dist_sink.h
include/spdlog/sinks/sink.h

Added a log_level per sink. See discussion here https://github.com/gabime/spdlog/issues/79
To be logged, a message should pass the check of the logger AND the sync.

Loglevel per sink

---

.gitignore
example/example.cpp
example/jni/Android.mk
example/jni/Application.mk
example/jni/example.cpp
include/spdlog/details/os.h
include/spdlog/details/spdlog_impl.h
include/spdlog/sinks/android_sink.h
include/spdlog/spdlog.h

2 errors will occur during `ndk-build`, in the original version.
```
In file included from spdlog/include/spdlog/details/log_msg.h:9:0,
from spdlog/include/spdlog/sinks/sink.h:9,
from spdlog/include/spdlog/sinks/base_sink.h:13,
from spdlog/include/spdlog/logger.h:15,
from spdlog/include/spdlog/spdlog.h:13,
spdlog/include/spdlog/details/os.h: In function 'std::string spdlog::details::os::errno_str(int)':
spdlog/include/spdlog/details/os.h:352:57: error: invalid conversion from 'int' to 'const char*' [-fpermissive]
return std::string(strerror_r(err_num, buf, buf_size));
```
```
spdlog/include/spdlog/fmt/bundled/format.h:3263: error: undefined reference to 'localeconv'
```
The pull request fixes the errors above.

Fix compilation on Android.

---

include/spdlog/details/os.h

_fstat() always fails under older 32bit WinXP/Win2003 targets.
_filelength() just works for both WinXP SDK and later Win7+ 32bit targets.

update os.h to fix filesize() on older win32

---

include/spdlog/details/async_log_helper.h
include/spdlog/details/os.h

Oracle Developer Studio 12.5 is fully C++11 capable, and these two changes enabled me to compile and use spdlog in my application.

Compatibility with Oracle Developer Studio 12.5 on  Solaris

---

CMakeLists.txt

- show list of headers in IDEs
- use a standard option for controlling building of tests
- enable build warnings on GCC and Clang
Feel free to reject any of these and cherry-pick the individual commits if you disagree for some reason.

cmake: misc improvements

---

include/spdlog/details/os.h

fixed compilation error in clang before version 8 (does not support thread_local keyword)
`thread_local` keyword just be supported in the Xcode 8 Beta and GM releases. (clang 8)
References:
https://stackoverflow.com/questions/23791060/c-thread-local-storage-clang-503-0-40-mac-osx/37817455#37817455
https://developer.apple.com/videos/play/wwdc2016/405/
http://devstreaming.apple.com/videos/wwdc/2016/405i2ilotov3bazyei1/405/405_whats_new_in_llvm.pdf

fixed compilation error in clang before version 8

---

include/spdlog/details/os.h

I have re-examined the clang's official documents.
[http://clang.llvm.org/docs/LanguageExtensions.html#builtin-macros](http://clang.llvm.org/docs/LanguageExtensions.html#builtin-macros)
It told me that, the marketing version numbers should not be used to check for language features, as different vendors use different numbering schemes. Instead, use the [Feature Checking Macros](http://clang.llvm.org/docs/LanguageExtensions.html#langext-feature-check).
[http://clang.llvm.org/docs/LanguageExtensions.html#c-11-thread-local](http://clang.llvm.org/docs/LanguageExtensions.html#c-11-thread-local)
There is a official example to determine if support for thread_local variables.
[http://clang.llvm.org/docs/LanguageExtensions.html#has-feature-and-has-extension] …

Use the feature checking macros to detect thread_local support in clang.

---

CMakeLists.txt

This is helpful when using spdlog as a dependency (git submodule) when a
master project is not interested in spdlog tests. Using
"BUILD_TESTING" name may create a confusion.
Extra: BUILD_EXAMPLE variable already have a prefix.

Add prefix for BUILD_TESTING cmake option

---

include/spdlog/details/pattern_formatter_impl.h

This improves thread-safety : we have the guarantee from the standard that the variable will be initialized on first use.
See http://stackoverflow.com/questions/1661529/is-meyers-implementation-of-singleton-pattern-thread-safe

Replace static global std::string arrays by Meyer singletons. 

---

include/spdlog/details/pattern_formatter_impl.h

There are some warnings in example codes.
Using double-braces solves them.
```
c++ example.cpp -o example -Wall -Wshadow -Wextra -pedantic -std=c++11 -pthread -I../include -O3 -march=native 
In file included from example.cpp:9:
In file included from ../include/spdlog/spdlog.h:14:
In file included from ../include/spdlog/logger.h:15:
In file included from ../include/spdlog/sinks/base_sink.h:14:
In file included from ../include/spdlog/formatter.h:44:
../include/spdlog/details/pattern_formatter_impl.h:85:34: warning: suggest
braces around initialization of subobject [-Wmissing-braces]
...const days_array arr{ "Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat" };
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
{                                              } …
```

Use double-braces in std::array initialization.

---

include/spdlog/details/logger_impl.h
include/spdlog/logger.h

Fix for #256 
As variadic template arguments can be zero length, we need to specify that at least one fmt argument is provided, to distinguish these methods from the existing trivial method that takes no fmt arguments.
Without this, static analysers such as ReSharper flag the logging calls as errors.

Disambiguate fmt logging methods that are using variadic templates.

---

include/spdlog/sinks/android_sink.h

added use_raw_msg flag to android_sink with default value (false) indicating raw/formatted msg
#421

Android_logger conditionally apply its own formatting

---

include/spdlog/details/os.h

On Alpine (and potentially other systems) that don't identify their runtime correctly there is an issue with the string conversion
Specifically, alpine linux and musl where the errno_to_string is incorrectly called.
To fix this I have added two overloaded functions and use auto err to allow the compiler to detect the actual types returned and call the correct method for conversion
Fixes #435

Allow compiler to select an strerror_r stringify

---

include/spdlog/sinks/wincolor_sink.h

Fix for MinGW 5.3.0 compilation error:
[ 12%] Building CXX object tests/CMakeFiles/catch_tests.dir/errors.cpp.obj
In file included from C:/projects/spdlog/include/spdlog/details/spdlog_impl.h:20:0,
from C:/projects/spdlog/include/spdlog/spdlog.h:178,
from C:\projects\spdlog\tests\includes.h:13,
from C:\projects\spdlog\tests\errors.cpp:4:
C:/projects/spdlog/include/spdlog/sinks/wincolor_sink.h: In destructor 'virtual spdlog::sinks::wincolor_sink<Mutex>::~wincolor_sink()':
C:/projects/spdlog/include/spdlog/sinks/wincolor_sink.h:47:15: error: there are no arguments to 'flush' that depend on a template parameter, so a declaration of 'flush' must be available [-fpermissive]
flush();
^
C:/projects/spdlog/include/spdlog/sinks/wincolor_sink.h:47:15: note: (if you use '-fpermissive', G++ will …

Fix for MinGW error: 'There are no arguments that depend on a template parameter'

---

include/spdlog/details/registry.h
include/spdlog/details/spdlog_impl.h
include/spdlog/spdlog.h

As mentioned in #458 this adds `create_async` functions to allow convenient creation/registration of async loggers without flipping the global async mode switch.

Add create_async factory functions for async loggers

---

include/spdlog/sinks/wincolor_sink.h

Keep the background color unchaged on Windows console when using colored loggers.

Background color unchanged

---

tests/cond_logging.cpp

Hi,
This is a PR for a minor code change which used to show warning in GCC.

Issue-488: warning for missing enumeration value

---

CMakeLists.txt

I encountered an issue when using spdlog through add_subdirectory.
Since SPDLOG_BUILD_TESTING is ON by default, it now adds tests to my project, even if BUILD_TESTING (the official CTest variable) is set to OFF.
cmake_dependent_option makes it so that if someone enables BUILD_TESTING then SPDLOG_BUILD_TESTING will be set to ON by default.
This way one can disable all external tests by setting only BUILD_TESTING before using add_subdirectory and then setting it back to its original value.
The only change for those using the library directly is that they now use BUILD_TESTING instead of SPDLOG_BUILD_TESTING when configuring.

SPDLOG_BUILD_TESTING now depends on BUILD_TESTING

---

include/spdlog/spdlog.h

Format source filename/line number in SPDLOG_TRACE output according to the compiler's convention it has been compiled under: filename(line_number) for MSVC, filename:line_number for others (GCC-style).

Compiler-dependent line numbering

---

include/spdlog/details/pattern_formatter_impl.h

For some of the logging we do the timestamps need to be in unix epoch.  I added a %E formatter that returns the epoch in seconds and figured it may be useful to others.  Since the chrono library is used, getting additional precision can be added using the already existing %e and %f formatters. Great library!

add formatter for unix epoch time in seconds.

---

include/spdlog/details/logger_impl.h

Fix SPDLOG_WCHAR_TO_UTF8_SUPPORT wchar_t logging

---

include/spdlog/details/mpmc_bounded_q.h

I've fixed several warnings (-Wold-style-cast in gcc) and did casting in C++ style.

Fix warnings which are caused by C style cast

---

include/spdlog/common.h
include/spdlog/details/logger_impl.h

On Linux with pthread library spdlog causes an SIGABORT and crashes
the application in case it catches a thread specific cancellation
exception in a critical execution phase while in a try/catch block
in spdlog/detail/logger_impl.h
The exception is caught by some general catch(...) clause where
it is NOT rethrown.
However rethrowing these kind of exception is mandatory, otherwise
an abort will be caused by the glibc.

rethrow unwind exception

---

include/spdlog/common.h

I'm building envoy, which uses spdlog, using current android NDK and cmake - ran into this error.

Allow compilation on platforms with unwind (android)

---

include/spdlog/details/mpmc_bounded_q.h

Modify `unsigned front, front1, back;` to `size_t front, front1, back;`

Declare variables as size_t rather than unsigned.

---

include/spdlog/async_logger.h
include/spdlog/common.h
include/spdlog/details/async_log_helper.h
include/spdlog/details/async_logger_impl.h
include/spdlog/details/file_helper.h
include/spdlog/details/log_msg.h
include/spdlog/details/logger_impl.h
include/spdlog/details/mpmc_bounded_q.h
include/spdlog/details/os.h
include/spdlog/details/pattern_formatter_impl.h
include/spdlog/details/registry.h
include/spdlog/details/spdlog_impl.h
include/spdlog/fmt/fmt.h
include/spdlog/fmt/ostr.h
include/spdlog/formatter.h
include/spdlog/logger.h
include/spdlog/sinks/android_sink.h
include/spdlog/sinks/ansicolor_sink.h
include/spdlog/sinks/base_sink.h
include/spdlog/sinks/dist_sink.h
include/spdlog/sinks/file_sinks.h
include/spdlog/sinks/msvc_sink.h
include/spdlog/sinks/null_sink.h
include/spdlog/sinks/ostream_sink.h
include/spdlog/sinks/sink.h
include/spdlog/sinks/stdout_sinks.h
include/spdlog/sinks/syslog_sink.h
include/spdlog/sinks/wincolor_sink.h
include/spdlog/spdlog.h

Paths pointing to the root of the library where replaced for ones relatives to each file.
For example, inside `/include/spdlog/details/file_helper.h:`
`#include "spdlog/details/os.h"`
This will look for `os.h` in `/include/spdlog/details/spdlog/details/` which doesn't exists.
replaced with:
`#include "../details/os.h"`
and similar for all the files

modified path on quoted #includes

---

include/spdlog/sinks/syslog_sink.h

Allow syslog to build by fixing include name.

correct include path for sink/syslog_sink.h

---

include/spdlog/sinks/wincolor_sink.h

See: https://github.com/gabime/spdlog/issues/595
On line 85 in file sinks/wincolor_sink.h:
```
back_color &= ~(FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_BLUE |
FOREGROUND_INTENSITY);
```
'back_color' is of type 'WORD' (unsigned short) whereas a bitwise
complement/NOT returns an int. This results in a conversion warning with
-Wconversion enabled.
```
85:20: warning: conversion to 'WORD {aka short unsigned int}' from 'int'
may alter its value [-Wconversion] back_color &= ~(FOREGROUND_RED |
FOREGROUND_GREEN | FOREGROUND_BLUE | FOREGROUND_INTENSITY);
```
Possible solution:
We know that the result of ~(FOREGROUND_RED | FOREGROUND_GREEN |
FOREGROUND_BLUE | FOREGROUND_INTENSITY) is always within the limits of
an unsigned short so a simple cast should suffice (correct me if I'm
wrong):
``` …
```

Issue fix for spdlog #595. Conversion warning.

---

include/spdlog/details/registry.h
include/spdlog/details/spdlog_impl.h
include/spdlog/spdlog.h

This provides a way to set the flush level for all loggers. It replicates the interface and implementation of the `set_level` free function.
I set the default flush level to `off`, which is what `logger_impl` defaults to, so there should be no change of behavior.

Add global flush_on function

---

include/spdlog/spdlog.h

Currently, the `SPDLOG_TRACE` and `SPDLOG_DEBUG` expand to nothing if they are disabled, but this can lead to problems. `assert` expands to `(void)0` when `NDEBUG` is defined, so I use the same here.
A couple of possible problems that could happen with the current definitions:
This is valid when `SPDLOG_DEBUG_ON` is defined, but expands to `,;` (which is an error) if not:
```
SPDLOG_DEBUG(logger, "x = {}", x), SDPLOG_DEBUG(logger, "y = {}", y);
```
If `SPDLOG_DEBUG_ON` is defined, this is a compilation error, but if not defined then then if statement actually catches the assignment to `b`:
```
bool b;
if (b)
SPDLOG_DEBUG(logger, "b was true")
b = false;
````

Ensure marcos always expand to expressions

---

include/spdlog/sinks/ansicolor_sink.h

Hey there 👋 
This PR does the following:
- Renames `gray` to `black` as it is more accurate (`30m` is officially specified as "black")
- Removes needless zeros from the `reset` code
- Clears the line after writing a log message, which fixes `->critical()` log messages bleeding their background color onto the new line. This is because the log messages have the newline _before_ the reset code, thus forcing most xterm-compliant emulators to paint the entire next line red before writing the next log message.
Before:
After:

A few small ANSI color improvements

---

example/example.cpp

This is a simple thing but the spelling mistake was bugging me :)

Fixed spelling mistake in example.cpp

---

tests/CMakeLists.txt

I have started working on #120 and I have found that CMake script in `/tests` was written in old fashioned way, so I ported it to modern CMake

Modern CMake in /tests

---

include/spdlog/sinks/wincolor_sink.h

For our application, we need to possibility to configure the defaul colors for the wincolor sink. Instead of forking the entire class, I think it makes more sense to keep this function public. 
The history seems to indicate that it was not made protected on purpose

Make set_color public in wincolor_sink to retain configurability

---

include/spdlog/sinks/file_sinks.h

Fix compilation error with GCC 8.0.1 
```
error: need 'typename' before 'std::conditional<std::is_same<char, char>::value, fmt::BasicMemoryWriter<char>, fmt::BasicMemoryWriter<wchar_t> >::type' because 'std::conditional<std::is_same<char, char>::value, fmt::BasicMemoryWriter<char>, fmt::BasicMemoryWriter<wchar_t> >' is a dependent scope
std::conditional<std::is_same<filename_t::value_type, char>::value, fmt::MemoryWriter, fmt::WMemoryWriter>::type w;
```

Fix compilation error with GCC 8

---

CMakeLists.txt
example/CMakeLists.txt
tests/CMakeLists.txt

Hey, a few changes to cmake files.
Marking project as CXX will disable detecting C compiler and other C related checks.
'INCLUDES DESTINATION' adds paths to 'INTERFACE_INCLUDE_DIRECTORIES' which is where include paths already are in spdlog target.
Bumped example's cmake version to 3.1.
Both test and example CMakeLists were using CRLF, changed to LF to match other source files.

CMake explicit language

---

tests/catch.hpp

Compiling with -Wmisleading-indentation triggers warning:
/data/Git/spdlog/tests/catch.hpp: In member function ‘bool Catch::TestSpec::Filter::matches(const Catch::TestCaseInfo&) const’:
/data/Git/spdlog/tests/catch.hpp:2913:17: warning: this ‘for’ clause does not guard... [-Wmisleading-indentation]
for( std::vector<Ptr<Pattern> >::const_iterator it = m_patterns.begin(), itEnd = m_patterns.end(); it != itEnd; ++it )
^~~
/data/Git/spdlog/tests/catch.hpp:2916:21: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the ‘for’
return true;
^~~~~~

Fix indentation in tests/catch.hpp:2916

---

include/spdlog/details/logger_impl.h
include/spdlog/details/os.h
include/spdlog/details/pattern_formatter_impl.h
include/spdlog/formatter.h
tests/format.cpp

Allow users to specify a custom EOL per pattern formatter. This will still use the system default if unspecified. Test cases pass.

Support for custom EOL per formatter

---

include/spdlog/sinks/syslog_sink.h

Fix for some annoying warnings when using `-Wsign-conversion` with clang

Fix implicit conversion warnings (-Wsign-conversion)

---

include/spdlog/common.h
tests/test_misc.cpp

Configure log level using name. (trace, debug, info...)
Creation a new function to convert level_enum from string  - **to_level_enum(const char*)** 
``` cpp
spdlog::level::level_enum lvl = spdlog::level::to_level_enum("debug");
```

New function to convert level_enum from string

---

tests/utils.cpp

Otherwise clang's static analyzer gives me the following warning:
```
spdlog-0.16.3/tests/utils.cpp:11:10: warning: Value stored to 'rv' during its initialization is never read
auto rv = system("mkdir -p logs");
^~   ~~~~~~~~~~~~~~~~~~~~~~~
```

Silence warning "value stored to rv is never read"

---

include/spdlog/contrib/sinks/step_file_sink.h

Hey. 
I started testing step_logger on the production server. I noticed that there is not enough possibility to write a header for the creation of the CSV files, and since the files are written with a limitation in volume and time, it is not the best option to add it from outside. :) 
Therefore, himself a logger.

Added file header support for step_logger

---

include/spdlog/contrib/sinks/step_file_sink.h

Hey.
Corrected the logger, the past addition caused problems with multithreading. Added also protection against unstable recording speed: if the specified maximum file size is so small that when the new file is selected, the names coincide. Now, in this case, the file size can exceed the maximum volume.

Update step logger

---

include/spdlog/common.h
include/spdlog/details/os.h

This fix uses the fmt::safe_strerror instead of the underlying
strerror_r functionality. I think this is better - but I'm not
sure if there is a reason for avoiding the use of this function.

Closes #717

---

include/spdlog/sinks/dist_sink.h

This allows users to set exactly the sinks they want, even if other unknown application code has added bespoke sinks in the meantime.

add remove_all_sinks method to dist_sink

---

include/spdlog/details/circular_q.h
include/spdlog/details/mpmc_blocking_q.h
include/spdlog/details/thread_pool.h
tests/test_async.cpp

Increment a counter every time a message is overridden so that users can inspect and adjust their queue sizes accordingly.
In my specific use case I don't mind losing a few messages every once in a while but I'd rather not lose any so at the end of the day I pull the counter and issue an alert if the counter is greater than zero and adjust the queue size for the next day.

Expose a counter for how many messages were dropped in async mode

---

include/spdlog/details/console_globals.h

Fixes #803 
@gabime I was also thinking of including just the windows.h, up to you.

Add missing include in console_globals.h

---

include/spdlog/details/os.h

Hello! I don't know why is the file open mode set to _SH_DENYWR in Windows, but it prevents to read the file when it is being used by the logger.
I have just changed the mode to _SH_DENYNO and it seams to work perfectly in all my production environments.

WIN32: Don't deny access to file sinks from other processes

---

include/spdlog/sinks/dist_sink.h

This allows users to set exactly the sinks they want, even if other unknown application code has added bespoke sinks in the meantime.
(This is a re-submission of #735, which was merged against the master (v0.x) branch.)

Add set_sinks method to dist_sink

---

README.md

Reverts gabime/spdlog#822
The conda contains very old spdlog version

Revert "Add `conda` to package managers in README"

---

CMakeLists.txt

The value is based on whether _spdlog_ is used as a third-party dependency or as a standalone project. If _spdlog_ is included through `add_subdirectory`, the tests/examples/benchmarks are disabled by default, and if _spdlog_ is configured standalone, then the tests are enabled by default.
Closes #830. (I did not talk about examples/benchmarks in that issue, however the logic is the same, these are not needed when _spdlog_ is a third-party dependency.)

Change the default value for SPDLOG_BUILD_xxx

---

include/spdlog/sinks/ansicolor_sink.h

Hello!
Looks like this include was missed!
Thanks!

ansicolor_sink.h - add missing sink include

---

example/CMakeLists.txt

Not sure what the interest is in this PR but I found that building for Android fails for me out-of-the-box when cross-compiling using the NDK. The error message is:
```
$: cmake --build . 
Scanning dependencies of target multisink
[  4%] Building CXX object example/CMakeFiles/multisink.dir/multisink.cpp.o
[  8%] Linking CXX executable multisink
[  8%] Built target multisink
Scanning dependencies of target example
[ 13%] Building CXX object example/CMakeFiles/example.dir/example.cpp.o
[ 17%] Linking CXX executable example
/tmp/bar/spdlog/include/spdlog/sinks/android_sink.h:56: error: undefined reference to '__android_log_write'
/tmp/bar/spdlog/include/spdlog/sinks/android_sink.h:61: error: undefined reference to '__android_log_write'
collect2: error: ld returned 1 exit status
make[2]: *** …
```

Add dependency to Android's log target in CMake

---

include/spdlog/details/os.h

For some reason, `_fstat64` fails with errno 22 on Windows Server 2003 x64 (and probably Windows XP x64 as well) when compiled using the `v141_xp` toolset.
Using `_filelengthi64` instead solves this issue.

Fix exceptions on file size calculation on Windows XP x64 and Windows Server 2003 x64

---

include/spdlog/common.h
include/spdlog/details/log_msg.h

Two warnings fixed:
* incorrectly default'ing operator= in a struct with a const data member (removed the line)
* implicitly casting an int to a uint32_t; I suppose that ideally the cast shouldn't be necessary
to begin with, but while it is still being done, better to have it explicit.  This also fixes a warning.

Fix some minor warnings found with a recent clang version

---

example/example.cpp

I've changed the alignment character in the example to illustrate left alignment of text. Originally, the alignment was right.

Corrected the text alignment in the example

---

CMakeLists.txt
cmake/Config.cmake.in

Using an external fmt lib should cause the spdlog::spdlog target to have
a dependency on fmt lib - so that a consuming project does not need
to call find_package(fmt) and target_link_libraries(... fmt::fmt).
To this end a new cmake option SPDLOG_FMT_EXTERNAL is introduced which
makes spdlog depend on fmt lib and defines the SPDLOG_FMT_EXTERNAL macro
to avoid using the bundled fmt lib. The value of SPDLOG_FMT_EXTERNAL is
also stored in the installed spdlogConfig.cmake and if it is ON
find_dependency() is used to ensure the fmt::fmt target is imported.
This was discovered in the context of vcpkg which always uses external fmt lib, but required consuming projects to handle the dependency - see Microsoft/vcpkg#4994

Fix handling of external fmt lib

---

CMakeLists.txt

Building the benchmarks requires google-benchmark to be installed which is
not the case for most of the build systems. The option now has a tiny
hint what the requirement is and where to get it.
[ccmake configuration example](https://i.imgur.com/12BzEOk.png)
closes #975

Disable building benchmarks by default

---

CMakeLists.txt
include/spdlog/common.h

Hi,
This pull request is certainly not a priority, but I modified slightly common.h so to remove some compile warnings, that are problematic for projects that build with -Werror.
Thought I would share this simple fix. 
When including the following logging utilities and the compile flag:
**-Wshadow**
#include "spdlog/sinks/stdout_color_sinks.h"
#include "spdlog/sinks/basic_file_sink.h"
To reproduce the errors without this pull request:
- add the compile flag -Wshadow
I know the naming of the parameters, starting with "t_" might be controversial.
Best,
Charles-David

Shadowed parameter

---

CMakeLists.txt

Fixes #982 
Tested to work well on Windows and Ubuntu and the newest versions of fmtlib. But coverage has been limited. Really curious what the CI will tell...

Allow the inclusion of an external fmtlib as as sub_directory

---

include/spdlog/sinks/sink.h

Sink's constructor should accept formatter interface just like set_formatter member function.

Allow custom formatter in sink's ctor

---

include/spdlog/details/logger_impl.h
include/spdlog/logger.h

Looks like one of the log functions is unnecessary since the "enable_if" check is later performed for log(source_loc...) version.

Remove unnecessary log function

---

CMakeLists.txt

This change makes it cleaner to use `spdlog` with CMake's `add_subdirectory` command (e.g. including it in the project tree as a Git submodule). Previously, `spdlog` headers etc. would be installed along with the outputs from the super-project.
Testing in my own project, this change doesn't seem to break anything, but that's hardly proof-positive that it won't ruin someone's day, somewhere, sometime.

Add CMake option for conditional installation

---

include/spdlog/sinks/ansicolor_sink.h

As described in #1004 it would be nice to have the private member `should_do_colors_` exposed.

Expose should_do_colors_ in ansicolor_sink.h

---

include/spdlog/sinks/systemd_sink.h
tests/test_systemd.cpp

The *test_systemd.cpp* is added, but is not linked. It requires *systemd* library, and I am not sure it is a good idea to add it unconditionally to the tests. And I am too lazy write CMake configuration for the *systemd* dependency.
Also, there is a code duplication with *syslog_sink.h*. The syslog sink also uses "syslog_priorities", but I cannot use directly. So a special function *syslog_level()* was introduced.

Add systemd sink.

---

include/spdlog/details/os.h

Hi,
This is trivial change. In a large codebase where I use spdlog, I had to do this change. I know this is not at all a bug in spdlog but this could save trouble where people have to deal with large codebases and namespace abuses (In my case, a few _bad_ "using namespace My_NAME" directives, where MY_NAME contains a stat() function and fixing it will take quite some effort).
If nothing else, this makes it explicit that POSIX functions from global namespace are used.
Thanks.

Namespace qualify stat functions

---

include/spdlog/spdlog.h

Old macros caused trouble if used in if-statements with an else-block not wrapped in curly braces.
See issue #1052 and referenced stackoverflow posts.

Fix unexpected log macro expansion

---

CMakeLists.txt

With this, people who want to use the header-only variant of external `fmt` library can do so.
This change should be "safe" as the old behavior is preserved.

Add a CMake option to use a header-only external fmt

---

include/spdlog/details/pattern_formatter.h

I'm compiling my code with [`-Wextra-semi`](https://clang.llvm.org/docs/DiagnosticsReference.html#wextra-semi) which causes warnings in one of spdlog's headers.
I haven't added `-Wextra-semi` in spdlog's CMakeLists.txt since it's only supported by newer GCC and Clang versions.

Remove unnecessary semicolons (-Wextra-semi)

---

include/spdlog/common.h
include/spdlog/sinks/ansicolor_sink.h
include/spdlog/sinks/stdout_color_sinks.h
include/spdlog/sinks/wincolor_sink.h

This adds a member function `ansicolor_sink::force_color_output` which can be used to force the output of color codes even when no TTY with color support is detected, as discussed in #1074. The `std[out|err]_color_[mt|st]` factory functions now support an optional argument `force_color_output` (which defaults to `false`) to make it more convenient to set this option directly upon construction.
As per @gabime's request I didn't add a new parameter to `ansicolor_sink`'s constructor, which makes the factory functions a bit clunky, but I tried to keep everything DRY.

Add option to force color output without TTY

---

include/spdlog/details/os.h

Adding `!defined(__HAIKU__)` to os.h allows for use on [Haiku](https://www.haiku-os.og).

Added !defined(__HAIKU__) to #if for stat64 struct.

---

include/spdlog/sinks/stdout_sinks.h

Snippet (includes sorted by clang-format):
```c++
#include <spdlog/sinks/stdout_sinks.h>
#include <spdlog/spdlog.h>
int main()
{
auto sink = std::make_shared<spdlog::sinks::stdout_sink_mt>();
auto my_logger = std::make_shared<spdlog::logger>("mylogger", sink);
}
```
Result:
```
/usr/local/include/spdlog/sinks/stdout_sinks.h:15: error: invalid use of incomplete type ‘class spdlog::sinks::sink’
class stdout_sink_base : public sink
^~~~
```

Fix use of incomplete type in stdout sinks

---

include/spdlog/sinks/systemd_sink.h
tests/CMakeLists.txt
tests/test_systemd.cpp

This PR includes support to send source code location information to the journal.
It replaces `sd_journal_print` with `sd_journal_send`, which allows more control over the journal's metadata.
If `spdlog-utets` contains `test_systemd.cpp`, the output may look like:
```
$ journalctl -r -o json-pretty _PID=20564 | jq -C 'select(.CODE_FILE != null)'
{
"_PID": "20564",
"_SYSTEMD_OWNER_UID": "1000",
"_CMDLINE": "tests/spdlog-utests -n systemd",
"_CAP_EFFECTIVE": "0",
"_TRANSPORT": "journal",
"_SYSTEMD_INVOCATION_ID": "db6561d285914cd59c2ee2e55bb786b4",
"_UID": "1000",
"_GID": "1000",
"_COMM": "spdlog-utests",
"CODE_LINE": "11",
"_SYSTEMD_USER_UNIT": "gnome-terminal-server.service",
"_SYSTEMD_CGROUP": "/user.slice/user-1000.slice/user@1000.service/gnome-terminal-server.service", …
```

Provide source location support for systemd_sink.h

---

include/spdlog/sinks/daily_file_sink.h

I noticed daily rotation was not worked when `SPDLOG_NO_DATETIME` is defined.
This PR will fix it :)

Fix rotation condition when SPDLOG_NO_DATETIME is defined.

---

.gitignore
bench/meson.build
example/meson.build
extract_version.py
meson.build
meson_options.txt
scripts/clang_tidy.sh
scripts/extract_version.py
scripts/format.sh
tests/meson.build

This PR adds support for the meson build system. This change allows easy inclusion of spdlog in meson projects. Additionally, most features from the current CMake build should also be supported.
A working example:
```
.
├── main.cpp
├── meson.build
└── subprojects
└── spdlog
```
meson.build:
```meson
project('mesonTest', ['cpp'])
sub = subproject('spdlog')
dep = sub.get_variable('spdlog_dep')
executable('main', ['main.cpp'], dependencies: [dep])
```
main.cpp:
```cpp
#include <spdlog/spdlog.h>
int main(int argc, char *argv[]) {
spdlog::info("Hello World");
return 0;
}
```
Build instructions:
```bash
cd /path/to/source/root
meson build
ninja -C build
./build/main
```

Add meson support

---

include/spdlog/sinks/ansicolor_sink-inl.h

This fixes the follows (compiler: clang-8):
```
...build/_deps/spdlog-src/include/spdlog/sinks/ansicolor_sink-inl.h:19:47: error: no member named
'pattern_formatter' in namespace 'spdlog'
, formatter_(details::make_unique<spdlog::pattern_formatter>())
~~~~~~~~^
...build/_deps/spdlog-src/include/spdlog/sinks/ansicolor_sink-inl.h:77:57: error: unknown type name
'pattern_formatter'
formatter_ = std::unique_ptr<spdlog::formatter>(new pattern_formatter(pattern));
```

Add missing include

---

include/spdlog/sinks/syslog_sink.h

payload does not appear to be reliably null terminated and leaks
data. Use size to the formatter to reliably terminate messages.

Fix syslog output

---

include/spdlog/details/os-inl.h

We recently encountered an issue in a project which has NEAR and FAR variables (constexpr in some namespace), after including spdlog.
Turns out that including `windows.h` leaks those, and that happened transitively through spdlog.
Now obviously this really is more of a Windows issue, but I think it would be convenient - especially for multi-platform users of spdlog - to prevent leakage of these symbols (with the same reasoning as e.g. for defining NOMINMAX). 
The required change is rather trivial.

Prevent NEAR and FAR macro definitions from leaking on Windows platforms

---

include/spdlog/async_logger-inl.h
include/spdlog/async_logger.h
include/spdlog/sinks/base_sink.h
include/spdlog/sinks/stdout_sinks-inl.h

This PR fixes two issues I recently encountered:
1. Following code triggers compilation error caused by missing include of `spdlog/details/pattern_formatter.h`.
```cpp
#include <spdlog/spdlog.h>
#include <spdlog/sinks/stdout_sinks.h>
int main()
{
std::make_shared<spdlog::sinks::stdout_sink_mt>();
}
```
2. Using templated constructor for `async_logger` along with building spdlog as a static library triggers linker error when:
a) We use anything else than `std::vector` iterators:
```cpp
#include <spdlog/async.h>
#include <spdlog/sinks/stdout_sinks.h>
#include <list>
int main()
{
std::list<spdlog::sink_ptr> sinks = {std::make_shared<spdlog::sinks::stdout_sink_mt>()};
std::make_shared<spdlog::async_logger>("logger", begin(sinks), end(sinks), spdlog::thread_pool());
}
```
Using vector as a …

Fix compiler and linker errors

---

include/spdlog/details/os-inl.h

Saw this warning cluttering my CI build logs. Shouldn't break anything since c style casts in C++ simply use the appropriate cast anyways. ([Reference](https://en.cppreference.com/w/cpp/language/explicit_cast))
[Example of the warning in CI build log](https://ci.appveyor.com/project/CppAndre/age/build/job/5gqj4sl6b33u03jf#L647)
Cheers and keep up the good work!

Fix use of old style cast in os-inl.h

---

include/spdlog/common.h
include/spdlog/logger.h
include/spdlog/spdlog.h

This adds a couple more overloads:
- One in `spdlog::log` which allows to pass a `source_loc` when passing an arbitrary `T` object
- One in `spdlog::log` which allows to pass a `source_loc` when using a wide character format string
- One in `spdlog::logger::log` which allows spdlog to avoid going through fmtlib when the type it is receiving is statically convertible to `wstring_view_t`.

Add more overloads to spdlog::log and spdlog::logger::log

---

include/spdlog/spdlog.h

... in macro SPDLOG_LOGGER_CALL

Remove extra semicolon

---

include/spdlog/sinks/wincolor_sink.h

`WriteConsole` can only be used with console handles whereas `WriteFile` can be used with other handles (such as files or pipes).
The reason this is useful is for the case when the C++ application making use of `spdlog` is being run as a subprocess in a larger system, eg using [Python's subprocess module](https://docs.python.org/3/library/subprocess.html) and you want the higher level process to receive the C++ application's stdout/stderr including `spdlog` output via a pipe.
When a pipe is used with `WriteConsole`, the call silently fails and no output is received by the calling process. With `WriteFile` the output is piped through as expected, and when running standalone, coloured output is written to the console as previously.
For further detail see: …

Windows color file sink: Use WriteFile rather than WriteConsole

---

CMakeLists.txt

Fixes #722 as CMake has added an option to disable enforcing 32/64-bitness parity for header-only libraries.

Added ARCH_INDEPENDENT option

---

include/spdlog/details/os-inl.h

Upstreaming https://github.com/DragonFlyBSD/DeltaPorts/blob/c9622be6d398/ports/devel/spdlog/dragonfly/patch-include_spdlog_details_os.h
Instead of `lwp_gettid` let's use `pthread_getthreadid_np` which is available on [AIX](https://www.ibm.com/support/knowledgecenter/en/ssw_ibm_i_74/apis/users_22.htm), [DragonFly](https://www.dragonflybsd.org/cgi/web-man?command=pthread_getthreadid_np&section=3), [FreeBSD](https://man.freebsd.org/pthread_getthreadid_np/3)

Unbreak on more BSDs

---

include/spdlog/common.h
include/spdlog/details/os-inl.h
include/spdlog/details/os.h

Definition of `wstring_view_t` no longer depends on `basic_string_view_t`

Fix #1239, Remove basic_string_view_t

---

CMakeLists.txt
cmake/spdlog.pc.in

Fixes https://github.com/gabime/spdlog/issues/1237.
Some things to note.
* I only tested this with the shared library, I am not sure if anything more needs to be done with the static library version or the header only version.
* The pkgconfig file expects `CMAKE_INSTALL_LIBDIR` to be a relative path, I am not sure there is a better way to handle this. It is important to retain the `{exec_prefix}/` and only append the relative library directory (i.e. `lib64`) for cross compiling.
* Its important to add `-DSPDLOG_FMT_EXTERNAL` to the `CFlags` when using an external fmt so that other projects that use `spdlog` find the correct headers when including `fmt.h`.
* This is enough to fix the `libixion` build, but currently they use the `spdlog.pc` file, the headers and not the library.
This is the …

cmake: Add a new spdlog.pc pkgconfig file.

---

CMakeLists.txt

This PR will change `make install` to skip the bundled fmt headers when `SPDLOG_FMT_EXTERNAL` is defined. This ensures that other projects will not silently use the bundled headers instead of the intended system fmt headers when including `fmt.h`. Also it avoids installing useless files when using the system fmt.
When `SPDLOG_FMT_EXTERNAL` is defined only these fmt headers will be installed.
```
usr/include/spdlog/fmt/
usr/include/spdlog/fmt/bin_to_hex.h
usr/include/spdlog/fmt/fmt.h
usr/include/spdlog/fmt/ostr.h
```
When `SPDLOG_FMT_EXTERNAL` is not defined these fmt headers will be installed.
```
usr/include/spdlog/fmt/
usr/include/spdlog/fmt/bin_to_hex.h
usr/include/spdlog/fmt/bundled/
usr/include/spdlog/fmt/bundled/LICENSE.rst
usr/include/spdlog/fmt/bundled/chrono.h …
```

cmake: Only install fmt headers when SPDLOG_FMT_EXTERNAL is not defined.

---

include/spdlog/details/pattern_formatter-inl.h

See https://github.com/gabime/spdlog/issues/1251
Stack Overflow says that putting parenthesis around std::max is a way to fix it, and I've seen this pattern used twice in the code base (actually in fmt library).
```
include/spdlog/fmt/bundled/printf.h
47:    return (std::max)(static_cast<int>(value), 0);
include/spdlog/fmt/bundled/format.h
1041:    int num_zeros = (std::max)(params.num_digits - full_exp, 1);
```
The type of the objects wasn't super clear so I went with the parenthesis option.

Fix windows compile error where std::max is overriden by a macro (#1251)

---

CMakeLists.txt

The library gets installed into ${CMAKE_INSTALL_LIBDIR}/spdlog, which
is for unix / linux a rather strange place, hence, put it where the linker
is more likely to find it.
Signed-off-by: Matthias Schoepfer <matthias.schoepfer@ithinx.io>

CMakeLists.txt: removed spdlog subdir from library install

---

include/spdlog/sinks/systemd_sink.h

Unlike the GNU C++ STL, there's no implicit include for <array> in this one, apparently.

Fix build failure on clang 7 with libc++

---

CMakeLists.txt
include/spdlog/async.h
include/spdlog/details/circular_q.h
include/spdlog/details/file_helper-inl.h
include/spdlog/details/os.h
include/spdlog/details/pattern_formatter-inl.h
include/spdlog/details/registry-inl.h
include/spdlog/details/registry.h
include/spdlog/logger-inl.h
include/spdlog/logger.h
include/spdlog/sinks/daily_file_sink.h
include/spdlog/spdlog-inl.h
include/spdlog/spdlog.h
meson.build
tests/test_macros.cpp
tests/test_registry.cpp

casese -> cases (1)
chache -> cache (1)
cirucal -> circular (1)
dependecy -> dependency (1)
detrmine -> determine (2)
eavluate -> evaluate (1)
exertnal -> external (1)
ony -> only (1)
registation -> registration (3)
registring -> registering (2)
regsistration -> registration (3)
seperate -> separate (2)
wit -> with (1)
withe -> with (1)

Fix some spelling errors.

---

tests/CMakeLists.txt

When cross-compiling spdlog from `x86-64` to `armhf`, I ran spdlog-utests via qemu-arm and noticed that the `daily_logger rotate` test was failing because `count_files` always returned zero.
Investigation of `count_files` revealed that `readdir` was returning nullptr immediately and setting errno to 75, i.e. "value too large for defined data type".  I suspected this had something to do with some 64 vs. 32-bit thing, so I added `_FILE_OFFSET_BITS=64` to the build and that seems to have made `readdir` (and the test) happy.
It might be safe to add `_FILE_OFFSET_BITS=64` for all Linux builds, but it only seems to be necessary for the 32-bit case (which is admittedly a fairly small audience -- I'm only building for armhf to target a Raspberry Pi 3 running Raspbian, which runs in 32-bit mode). …

Use _FILE_OFFSET_BITS=64 when building on Linux 32-bit systems

---

include/spdlog/sinks/systemd_sink.h

These three patches which make it easier to use `systemd`/`journald`'s structured logging. When everything is in place, one can, for example, watch the log stream via this user-friendly :) command:
```
journlctl -f -u my-app.service \
PRIORITY=1 PRIORITY=2 PRIORITY=3 PRIORITY=4 \
SYSLOG_IDENTIFIER=only-important-messages-are-shown-now \
+ \
PRIORITY=1 PRIORITY=2 PRIORITY=3 PRIORITY=4 PRIORITY=5 PRIORITY=6 PRIORITY=7 \
SYSLOG_IDENTIFIER=I-want-details-from-this
```
That command will follow journal stream from the `my-app.service`. The logger whose name is `only-important-messages-are-shown-now` is rather heavily filtered, but everything from a logger called `I-want-details-from-this` is shown. These options are [documented](https://www.freedesktop.org/software/systemd/man/journalctl.html) …

improve systemd journald support

---

include/spdlog/spdlog.h
tests/test_macros.cpp

Hello. I think the log macros should be changed to compile with "&my_logger" expressions. Thanks.

Improve log macros

---

include/spdlog/details/os-inl.h

`__cplusplus_winrt` only detected C++/CX (which can be used without compiling for UWP, SetHandleInformation would be available in those cases), and did not detect native UWP C++. This patch fixes that by using the WINAPI_FAMILY_PARTITION macro in the Windows SDK headers in the same way those headers remove SetHandleInformation in UWP builds.

Correctly guard SetHandleInformation API call

---

include/spdlog/details/circular_q.h
include/spdlog/sinks/ringbuffer_sink-inl.h
include/spdlog/sinks/ringbuffer_sink.h

Ringbuffer sink keeps user-given number of most recent log messages in
memory and returns them upon request (using the ringbuffer_sink::last
method). This can be useful for e.g. remote debugging of a running app.

Add ringbuffer sink

---

include/spdlog/spdlog.h

Remove redundant semicon of macro SPDLOG_LOGGER_CALL which causes clang diagnoses empty statement.

Remove redundant semicolon

---

README.md

The line
```
SPDLOG_TRACE("Some trace message with param {}", {});
```
which normally is discarded at the compile time since by deafult
`SPDLOG_ACTIVE_LEVEL` is at `SPDLOG_LEVEL_INFO`. If however, one goes
to `tweak.me` and sets
```
#define SPDLOG_ACTIVE_LEVEL SPDLOG_LEVEL_TRACE
```
suddenly the basic example does not compile any more.
This commit fixes the potential problem.

Fix a small problem in the basic example

---

meson.build

The option is: 'enable_tests_ho' as stated in meson_options.txt

Fix invalid meson option

---

meson.build

Now `fmt` library can be used as subproject which helps with cross
compilation.

meson: add fallback to fmt dependency

---

README.md

I am the maintainer of spdlog on MacPorts, now the latest version(1.4.2) of spdlog is available on MacPorts.

latest spdlog now available on MacPorts

---

tests/utils.h

This PR removes a duplicate line in `tests/utils.h`.

tests/utils.h: removed duplicate entry for count_lines()

---

tests/CMakeLists.txt

Ref #1419 
Change ctest not to execute `spdlog-utests` and `spdlog-utests-ho` in parallel.

Don't run spdlog-utests and spdlog-utests-ho in parallel

---

include/spdlog/details/os-inl.h
include/spdlog/details/os.h

Using the SPDLOG_PREVENT_CHILD_FD option there where still a race when
a other thread was using fork and exec in between the call to fopen and fcntl.
Using open and O_CLOEXEC when possible prevents this race.
I have no idea if this problem  exists on Windows.

Properly handling SPDLOG_PREVENT_CHILD_FD

---

include/spdlog/logger.h

calling log with a string_view as msg called
``` c++
template<typename... Args>
void log(source_loc loc, level::level_enum lvl, string_view_t fmt, const Args &... args)
```
instead of
``` c++
template<class T, typename std::enable_if<std::is_convertible<const T &, spdlog::string_view_t>::value, T>::type * = nullptr>
void log(source_loc loc, level::level_enum lvl, const T &msg)
```
which lead to an unnecessary call to fmt::format

adding additional log overload to prevent unnecessary fmt::format

---

tests/test_async.cpp
tests/test_daily_logger.cpp
tests/test_errors.cpp
tests/test_file_logging.cpp
tests/test_macros.cpp
tests/utils.cpp
tests/utils.h

This PR is currently a demo only. It is created against tag v1.5.0. It should show-case how one could add support for empty `SPDLOG_EOL` in the tests. This seems a "relatively" common request amongst users so it may be nice if the tests can support it.
Closes #1413 .

Make tests support empty SPDLOG_EOL

---

include/spdlog/tcp_sink.h

Implementation of tcp_sink. Can be used for remote log collectors.

tcp_sink implementation for fluentbit

---

include/spdlog/sinks/daily_file_sink.h
include/spdlog/sinks/rotating_file_sink-inl.h
include/spdlog/sinks/rotating_file_sink.h

`filename()` member function of file sink has no critical section but `spdlog::details::file_helper::filename_` member variable may be changed by calling `sink_it_()`.
This causes a multi-threaded data race.
Added a critical section to avoid data race.
No critical section has been added to  `spdlog::sinks::basic_file_sink::filename()` because `spdlog::sinks::basic_file_sink` doesn't  rotate, the file name doesn't change.

Add critical section to filename function of  each file sink

---

include/spdlog/sinks/win_eventlog_sink.h

Fixes #1432 and building under Windows. The `base_sink` scope is not examined as it is a dependent name, we must explicitly specify the scope.
https://eel.is/c++draft/temp.dep#4

Fix Windows event log sink

---

include/spdlog/common.h
include/spdlog/details/windows_include.h
include/spdlog/sinks/msvc_sink.h
include/spdlog/sinks/win_eventlog_sink.h
include/spdlog/sinks/wincolor_sink.h

Partial solution for issue https://github.com/gabime/spdlog/issues/1454

only include windows.h when it's unavoidable

---

include/spdlog/logger-inl.h

This isn't a fix for anything it's just a patch for an incorrectly flagged clang-tidy warning.
Description
------------
The latest version of clang-tidy contains the check `clang-analyzer-cplusplus.Move` which warns when a moved from object is deferenced.
The check incorrectly identifies a use after move within the spdlog function `logger::set_formatter` because it fails to detect that moving the pointer only occurs on the last iteration of the loop, assuming that it may call `clone()` on it later.
Details of the warning:
```
/3rdParty/spdlog-1.4.2/include/spdlog/logger-inl.h:96:34: warning: Moved-from object 'f' is moved [clang-analyzer-cplusplus.Move]
(*it)->set_formatter(std::move(f));
/3rdParty/spdlog-1.4.2/include/spdlog/sinks/stdout_color_sinks-inl.h:18:12: note: Calling …
```

Resolve erroneous clang-tidy warning about using a moved from pointer

---

include/spdlog/fmt/bin_to_hex.h
tests/test_misc.cpp

Support:
1. Show ASCII.
`spdlog::debug("{:a}", spdlog::to_hex(data.begin(), data.end()));`
2. Split output with different size per line.
`spdlog::debug("{:a}", spdlog::to_hex(data.begin(), data.end(), 16));`
`spdlog::debug("{:a}", spdlog::to_hex(data.begin(), data.end(), 8));`

Enhance to_hex like the hexdump command

---

README.md

spdlog is available on conda-forge for a long time.
https://anaconda.org/conda-forge/spdlog

README: add conda as a supported package manager

---

tests/test_cfg.cpp

Use the generic Windows macro here to fix compilation on non-MSVC toolchains. The `setenv` is not guaranteed available under MinGW and should also use `putenv`.

Fix Windows setenv check

---

CMakeLists.txt
cmake/pch.h.in

Precompiled headers can speed up compilation time by a lot.
Since CMake `3.16` there is a new function `target_precompile_headers` that handle precompiled header for every compilers. It's really easy to set up in the project, and doesn't required more step from final user.
I'm building `spdlog` as part of my CMake project, and since there are lots of target in the build, i'm trying to earn so time by using precompiled header for some target that are still not supporting it.
I did an implementation on my [fork](https://github.com/OlivierLDff/spdlog), branch is `pch-support`. And made some basic benchmark. 
I measured timing with msvc using built in build times measurement. [Example here](https://stackoverflow.com/questions/82128/displaying-build-times-in-visual-studio).
My processor is …

Support for precompiled headers with SPDLOG_ENABLE_PCH

---

README.md

Not maintained anymore: https://archlinux.fr/yaourt-en
Alternatively: spdlog is now apart of the community repo (https://www.archlinux.org/packages/community/x86_64/spdlog/)

yaourt is outdated and insecure, use yay in README.md

---

cmake/utils.cmake

clang on windows support both gcc and mscv style options. Clang.exe on windows
defaults to gcc style, which will result in /WX unknown compiler command.
This will set /WX if and only if the compiler is MSVC and greater than version 1900.
Could perhaps be done in a prettier way, but it solves the issue nicely.

add /WX mscv compiler option for only mscv compiler

---

CMakeLists.txt
cmake/utils.cmake

I recently started using spdlog in my personal project. I went with submodule + building with project approach. The problem I encountered is that there is no way to disable warnings that I get from spdlog files. So I added a cmake option to disable them for cases such as mine.

Added an option to disable compiler warnings

---

CMakeLists.txt

The used `fmt::fmt` target has been introduced with `fmt 5.0.0`.
Without this `spdlog` also picks up older versions of `fmt` like `4.0.0` on Ubuntu 18.04 through `libfmt-dev` or even older versions on Ubuntu 16.04 through `libfmt3-dev`. Compilation fails but the error message is not straight forward at all.
I'm not sure if the version should be higher depending on what features of `fmt` are used within `spdlog`.

Set minimum version of fmt to 5.0.0

---

include/spdlog/sinks/ringbuffer_sink.h

Fixed ringbuffer_sink last_raw and last_formatted giving the first lim number of elements instead of last.

Fixed ringbuffer_sink last_raw and last_formatted

---

include/spdlog/details/fmt_helper.h

See: https://github.com/fmtlib/fmt/issues/1538
Fixes: https://github.com/gabime/spdlog/issues/1604

fmt 7.0.0 renamed the internal namespace to detail.

---

CMakeLists.txt
bench/CMakeLists.txt
example/CMakeLists.txt
tests/CMakeLists.txt

Using a version range enables the policies up to the current version.
This fixes warnings due to deprecated policies in newer versions. Testing shows there to be no policy changes that are problematic.
A fallback is retained for versions <3.11 to emulate the version range behaviour.

Bump CMake requirement to 3.10, don't enable C language

---

include/spdlog/spdlog-inl.h
include/spdlog/spdlog.h

* Added: `spdlog::get_level()` API function - like `logger::level()`, except for the name change
* Added: `spdlog::should_log()` API function - like `logger: should_log()`
* Added some code to the example program to use the two new API functions.

Fix for issue #1627: Global get_level() and should_log()

---

include/spdlog/details/tcp_client.h

-> fix the issue that the head is not compilable bc. of missing declaration
-> optimize if/else block in connection function. Else not needed bc. of break in if

tcp_client.h bugfix for macOS and add tcp example

---

include/spdlog/cfg/env.h

Hi, is `cfg/env.h` intended to be included only once?

Make load_env_levels inline function

---

include/spdlog/logger-inl.h

As previously discusses, R much prefers to use its own (buffered) standard output and error output and flags it when compiled extensions use the library ones.  
This short PR switches the last remaining `fprintf()` out for R's own `REprintf()` (which is identical, apart from not needing the implicit `stderr`, and printing to R).  
We rely on two defines set in the top-level header file `R.h` which users (such as [RcppSpdlog](https://github.com/eddelbuettel/rcppspdlog)) should include _before_ including `spdlog/spdlog.h`.

let R header defines switch to REprintf over fprintf(stdderr)

---

bench/CMakeLists.txt

Currently building with `-DSPDLOG_BUILD_ALL=1` fails if googlebench is not installed on the user system (because `bench` depends on googlebench). CMake FetchContent can be used to download and build it (also test it, but I disabled that option) so that the bench build doesn't fail. FetchContent is however only available on CMake 3.11+, hence the hacky version check.
Obviously, the cleaner solution is to bump CMake minimum to 3.11, but I didn't change that because https://github.com/gabime/spdlog/pull/1624

Download googlebenchmark if not found 

---

include/spdlog/spdlog.h

Replacing a wrong `->` by `.` in a code comment. In the wiki the [same example](https://github.com/gabime/spdlog/wiki/1.1.-Thread-Safety#non-thread-safe-functions) is correct.

Fix typo in comment

---

include/spdlog/details/mpmc_blocking_q.h
include/spdlog/details/thread_pool-inl.h
include/spdlog/details/thread_pool.h

I want to monitor messages queue size, so I need such method into thread_pool.

Ability to get size of messages queue of async thread pool

---

README.md

Add {:a} format flag to bin_to_hex example

📝 README example: Add {:a} format flag to bin_to_hex example

---

tests/test_async.cpp

Increase sleep time on a test case to avoid spurious failures

---

include/spdlog/details/os-inl.h

I have the issue that the in the alacritty terminal spdlog has no colors,
so I added it the the supported terminals.
To be more generic I added also a check for the COLORTERM variable
which should also indicate if the terminal supports color.

Changed is_color_terminal to be more generic.

---

include/spdlog/sinks/wincolor_sink-inl.h
include/spdlog/sinks/wincolor_sink.h
tests/utils.cpp

ensure stdout color sinks do not leak windows headers with SPDLOG_COMPILED_LIB

---

CMakeLists.txt

`fmt` provides a config file, so there's no need to waste time trying module mode. Also, it would appear the `CONFIG` option was previously passed, [until being removed in what appears to be an accident?](https://github.com/gabime/spdlog/commit/6fe899af104930c381b8bb0498e93b7a09418241#diff-1e7de1ae2d059d21e1dd75d5812d5a34b0222cef273b7c3a2af62eb747f9d20aL71) In any case, there's no explanation for it, so I assume it will be fine to add it back.

skip module mode when finding fmt

---

include/spdlog/details/file_helper-inl.h

This is a possible implementation of https://github.com/gabime/spdlog/issues/1793
It passes unit tests, I'm not sure what else needs checking.

Open files with "ab" mode even if truncating.

---

include/spdlog/details/os-inl.h

NOMINMAX macro doesn't work everytime for some reason

better numeric_limits<>::max/min fix when using SPDLOG_WCHAR_TO_UTF8_SUPPORT

---

include/spdlog/sinks/daily_file_sink.h

example:
```cpp
std::shared_ptr<spdlog::logger> _logger = spdlog::daily_logger_format_mt ("module", "%Y%m%d.log");
_logger->info ("hahahaha");
```
then will create file `20210225.log`

add daily sink filename format

---

README.md

WARNING: Please do not merge yet! See below.
We are currently in the process of packaging `spdlog` for `build2`, we have it working (even on unsupported Windows, see for example: https://ci.stage.build2.org/@a993b64e-8ba2-422e-97d7-250cdb5828e0?builds=&pv=&tc=*&cf=&mn=&tg=&rs=*)
This change simply adds the necessary information to use this package when using `build2`. Some notes:
- not sure how to give the info succintly because `build2` allows packages to come from different sources, including the git repository of the package - in doubt I just linked to the future community repository address providing all the info, but the other package manager didn't do it like that so not sure if it's ok for you?; 
- `build2` distinguish the package (`depends: spdlog <some-version-scheme>`, added in …

Add build2 package support

---

CMakeLists.txt

This PR simply adds a flag for Windows build to change the target runtime (`/MT`/`/MD`).
The naming comes from SDL2's cmake: https://github.com/libsdl-org/SDL/blob/main/CMakeLists.txt#L226.
I based my tests with this doc: https://stackoverflow.com/a/19487637.

CMake: Add SPDLOG_STATIC_VCRT to choose static MSVC runtime

---

CMakeLists.txt

This is to avoid
`ld: error: undefined symbol: __android_log_write`

Add required libraries for Android CMake build

---

CMakeLists.txt

By introducing 'no module' support https://github.com/gabime/spdlog/commit/3d8f71c4d23fd2df08e4f6284155958b0df47b33 this inadvertently triggered the find_package to use the "full version" version selection.
From https://cmake.org/cmake/help/latest/command/find_package.html#version-selection:
> When the [version] argument is given, Config mode will only find a version of the package that claims compatibility with the requested version (see format specification).
FMT does not set this configuration https://github.com/fmtlib/fmt/blob/7.1.3/support/cmake/fmt-config.cmake.in... but regardless it would not be "any compatibility" based on version semantics.
Which causes this error. v1.8.2 builds perfectly fine.
```
CMake Error at CMakeLists.txt:181 (find_package):
Could not find a configuration …
```

Remove version requirement from fmt find_package

---

include/spdlog/pattern_formatter-inl.h

Comment describing the default logging pattern is missing [%s:%#], which is the abbreviated source file + the line number.
I tried to customize our own logger by copy pasting this info, and then I noticed we had lost that information.

Update pattern_formatter-inl.h full_formatter comment to describe the default logging pattern expression accurately

---

include/spdlog/sinks/stdout_sinks-inl.h

I'm also stuck at the problem described in issue #1790.
So the PR fix the problem as is in the issue, it just works.
By the way, fully remove **#include <fileapi.h>** is also ok, but as for the code consistency, I think keeping it is a better way.

fix bug #1790

---

include/spdlog/sinks/base_sink.h

Classes inheriting from `base_sink` can now lock the base mutex inside their `const` member methods (e.g., basic accessors).

Made mutex member variable mutable

---

include/spdlog/details/tcp_client-windows.h
include/spdlog/details/tcp_client.h

Changed some c-style casts to use reinterpret casts in tcp_client.h and tcp_client-windows.h. Similar to #1164.
Thanks.

Change c-style casts to reinterpret casts in tcp_client

---

include/spdlog/details/os-inl.h

All MSVS versions >= 2015 warn about "return 0" after throw_spdlog_ex()
being unreachable in filesize(), so disable this warning in this
function (note that it can't be disabled inside it).
---
Replaces #1927.

Avoid harmless warning about unreachable statement in MSVS build

---

include/spdlog/details/os-inl.h

This warning is disabled by default, but is pretty useful and worth
enabling for MSVC, just as -Wundef for gcc, so fix it in Win32 build.
---
Sorry for another trivial PR, but while testing #1930 I've also stumbled on this one in Win32 build.

Fix warning about testing _WIN64 which might be undefined

---

include/spdlog/common-inl.h

Signed-off-by: Rosen Penev <rosenp@gmail.com>

small std::find conversion

---

include/spdlog/common.h
include/spdlog/sinks/stdout_color_sinks-inl.h
src/async.cpp
src/cfg.cpp
src/color_sinks.cpp
src/file_sinks.cpp
src/spdlog.cpp
src/stdout_sinks.cpp

Using CMake, Nvidia's `nvc++` adds the `-A` compiler flag ("strict"), causing compilation error if newlines are missing from the end of source files. `nvc++` (not to be confused with `nvcc`) is detected as the PGI C++ compiler and this patch may therefore also apply to that. Proposed changes involve newlines, only.

Allow compilation with nvc++ (and possibly PGI)

---

include/spdlog/async.h
include/spdlog/details/file_helper.h
include/spdlog/details/os-inl.h
include/spdlog/details/os.h

When building under VS, I have:
```
[build] [...]\vcpkg\installed\x64-windows\include\spdlog\details\os-inl.h(362,25): warning C4365: 'argument': conversion from 'int' to 'DWORD', signed/unsigned mismatch [[...].vcxproj]
```
This small patch just fix it.
It should be compatible with `std::chrono::milliseconds` where the type of the argument is part of the template;

Fix signed/unsigned mismatch in VS

---

include/spdlog/details/registry-inl.h
include/spdlog/details/registry.h

```cpp
// error C2664: 'void spdlog::set_error_handler(void (__cdecl *)(const std::string &))': cannot convert argument 1 from '<lambda_1>' to 'void (__cdecl *)(const std::string &)'
//
spdlog::set_error_handler([&](const std::string &message) { /* ... */ });
spdlog::set_error_handler([=](const std::string &message) { /* ... */ });
```
The pure pointer function type error handler cannot store `lambda with capture` or `std::bind`.
I think this might be a mistake? Because the error handler in `spdlog::logger` is using `err_handler` (`std::function`).
This PR changes the global error handler type from a pure pointer function (`void (*)(const std::string &msg)`) to `err_handler` (`std::function<void(const std::string &err_msg)>`) to fix that problem.

Use std::function for the global error handler

---

include/spdlog/sinks/mongo_sink.h

Hello I've added custom sink for writing logs to mongodb.  If I will have free time I want to make dynamic mongodb document structure based on format string pattern.
* [mongocxx](http://mongocxx.org/mongocxx-v3/installation/)
```C++
#include <spdlog/async.h>
#include <spdlog/sinks/mongo_sink.h>
#include <spdlog/spdlog.h>
#include <thread>
int main() {
std::thread t1([&] {
auto logging = spdlog::async_factory::create<spdlog::sinks::mongo_sink>(
"mongo_logger_1", "db", "collection");
for (auto i = 0; i < 10; ++i) {
logging->info("thread_1 iter: {}",i);
std::this_thread::sleep_for(std::chrono::milliseconds(500));
}
});
std::thread t2([&] {
auto logging = spdlog::async_factory::create<spdlog::sinks::mongo_sink>(
"mongo_logger_2", "db", "collection");
for (auto i = 0; i < 10; ++i) { …
```

added mongodb sink

---

include/spdlog/details/os-inl.h

I am using spdlog in RISC-V64 machine,
and the COLORTERM in this machine is "vt102",
so open a pr

Add a color-terminal type

---

include/spdlog/logger.h

To reproduce, you will need to install clang 13 development branch:
```
mkdir build
cmake -DCMAKE_CXX_STANDARD=20 -DCMAKE_BUILD_TYPE=Debug -DSPDLOG_BUILD_TESTS=ON -DCMAKE_CXX_COMPILER=clang++-13 -DSPDLOG_BUILD_EXAMPLE=ON ..
make
...
spdlog/include/spdlog/logger.h:95:9: error: call to member function 'log' is ambiguous
log(source_loc{}, lvl, msg);
^~~
spdlog/include/spdlog/logger.h:238:9: note: in instantiation of function template specialization 'spdlog::logger::log<char [38]>' requested here
log(level::debug, msg);
^
spdlog/include/spdlog/spdlog.h:249:27: note: in instantiation of function template specialization 'spdlog::logger::debug<char [38]>' requested here
default_logger_raw()->debug(msg);
^
spdlog/example/example.cpp:43:13: note: in instantiation of function template …
```

Fix compilation error in clang 13 in C++20 mode - ambiguous call to log function

---

include/spdlog/sinks/qt_sinks.h

Removing 2 chars (CR/LF) is under Windows okay, but on Linux only one char (LF) has to be deleted. Otherwise a char of the content is removed. So the fix is to use the QString method `trimmed()` to remove the CR/LF or LF chars.

Trim the newline-chars instead of removing of 2 chars

---

include/spdlog/sinks/qt_sinks.h

Removed separate class layout for qt_sinks and also send logs to any custom qt (QObject) classes (QML, QFile, custom Widget etc.)

Added common class for all qt objects

---

include/spdlog/sinks/mongo_sink.h

mongo_sink.h used `std::make_unique` instead of `spdlog::details::make_unique`, thus making it impossible to compile a project under C++11 which spdlog itself targets. While mongocxx requires use of polyfills to work under C++11, it should not be a case with a spdlog project that just links with it

Removal of C++14-specific std::make_unique from mongo_sink.h

---

include/spdlog/details/thread_pool.h

there is one head file be included twice in the thread_pool.h, I just delete duplicate one.

fix include file twice in the same file

---

CMakeLists.txt
cmake/spdlogConfig.cmake.in

As per CMake's Importing and Exporting Guide[1],
configure_package_config_file() should be used for configuring the
package configuration file, not the regular configure_file() function.
This ensures that a spdlog package built on one system (with a given
directory tree) can be imported from a different system -
e.g. creating a pre-compiled spdlog package for use on different
systems.
[1]: https://cmake.org/cmake/help/git-stage/guide/importing-exporting/index.html#id8

Ensure exported package is relocatable

---

include/spdlog/common-inl.h

std::distance internally runs a loop, which may or may not be optimized
away. Just use simple arithmetic.
Signed-off-by: Rosen Penev <rosenp@gmail.com>

remove std::distance usage

---

include/spdlog/fmt/bin_to_hex.h

The goal is to support inclusion of `bin_to_hex.h` in any order with `spdlog.h`
PROBLEM FIXED (UNWANTED COMPILATION BEHAVIOR):
Some projects require sorting inclusions in alphabetical order. But in case one includes `<spdlog/fmt/bin_to_hex.h>` prior to `<spdlog/spdlog.h>`, multiple compilation errors arise:
* `bin_to_hex.h:35:45: error: ‘size_t’ has not been declared`
* `bin_to_hex.h:59:42: error: ‘begin’ is not a member of ‘std’`
* `bin_to_hex.h:59:65: error: ‘end’ is not a member of ‘std’`
* `bin_to_hex.h:83:5: error: ‘FMT_CONSTEXPR’ does not name a type`
* `bin_to_hex.h:115:9: error: ‘SPDLOG_CONSTEXPR’ was not declared in this scope`
and so on...
(My compiler is GCC 10.3)
This PR adds an include of `spdlog.h` into `bin_to_hex.h`, so they can be included in any order.

bin_to_hex.h: include spdlog.h 

---

README.md

Source makes me think the instruction is to copy `src`, not `include`. Changed the text accordingly.

The install instructions for "header only" refers to the wrong folder

---

include/spdlog/async_logger-inl.h
include/spdlog/logger-inl.h
include/spdlog/logger.h

Useful when formatting log messages fails. Now you can tell which log message caused the problem.

Added additional information for error handler

---

example/example.cpp
include/spdlog/details/udp_client-windows.h
include/spdlog/details/udp_client.h
include/spdlog/details/udp_client_windows.h
include/spdlog/sinks/udp_sink.h

This PR updates the prior udp_sink PR (#1746), cleaning up some code and adding initial Windows support.  Winsock seems more prone to drop UDP packets if sent too quickly, so this sink seems more usable on Linux.  I'm not a Windows developer so I'm not sure if I'm missing something.

Add udp_sink

---

CMakeLists.txt

I am no expert in all the policies, but I have seen no issues when using it with cmake 3.21.2.
My main user-case is getting `fmt_ROOT` to work (CMP0074).

CMake: Support <PackageName>_ROOT

---

example/example.cpp
include/spdlog/common.h
include/spdlog/details/file_helper-inl.h
include/spdlog/details/file_helper.h
include/spdlog/sinks/basic_file_sink-inl.h
include/spdlog/sinks/basic_file_sink.h
include/spdlog/sinks/daily_file_sink.h
include/spdlog/sinks/hourly_file_sink.h
include/spdlog/sinks/rotating_file_sink-inl.h
include/spdlog/sinks/rotating_file_sink.h

add file event handlers

---

include/spdlog/details/udp_client.h

We seem to be missing include file netinet/in.h in udp_client.h.
I've tested on Linux and FreeBSD, but don't have access to other platforms.

example.cpp failes to build on FreeBSD

---

example/example.cpp
include/spdlog/common.h
include/spdlog/details/file_helper-inl.h
include/spdlog/details/file_helper.h
include/spdlog/sinks/basic_file_sink.h
include/spdlog/sinks/daily_file_sink.h
include/spdlog/sinks/hourly_file_sink.h
include/spdlog/sinks/rotating_file_sink.h

file_event_handlers add before_open function

file_event_handlers add before_open function

---

include/spdlog/tweakme.h

Uncommenting `SPDLOG_FUNCTION` will make MSVC fail to compile,
Fixed it by adding an `#ifdef` around `__PRETTY_FUNCTION__`

Fix(tweakme): SPDLOG_FUNCTION

---

bench/async_bench.cpp
include/spdlog/details/os-inl.h

spdlog failed to compile on `AIX 7.2`
```
In file included from /~/spdlog/src/spdlog.cpp:12:
/~/spdlog/include/spdlog/details/os-inl.h:237:16: error: expected unqualified-id
int fd = ::fileno(f);
^
/usr/include/stdio.h:515:25: note: expanded from macro 'fileno'
#define fileno(__p)     ((__p)->_file)
^
In file included from /~spdlog/src/spdlog.cpp:12:
/~/spdlog/include/spdlog/details/os-inl.h:340:34: error: no member named 'pthread_getthreadid_np' in the global namespace
return static_cast<size_t>(::pthread_getthreadid_np());
~~^
1 warning and 2 errors generated.
```
with following configurations
```
export OBJECT_MODE=64
cmake .. -DCMAKE_C_COMPILER=xlclang -DCMAKE_CXX_COMPILER=xlclang++ -DCMAKE_POSITION_INDEPENDENT_CODE=ON
```
- `fileno` is a macro on AIX, so we cannot use `::` scope …

fix compiling errors on AIX

---

include/spdlog/common.h
include/spdlog/sinks/base_sink.h

-flto=thin -fvisibility=hidden -fno-sanitize-trap=cfi
See https://gcc.gnu.org/wiki/Visibility

Fix runtime when build with -fsanitize=cfi

---

README.md
example/example.cpp

Add example how to replace default logger.

---

example/example.cpp
include/spdlog/fmt/bin_to_hex.h

Hello!
First of all, thanks a lot for this great package!
I encountered a compile problem when using ranges and bin_to_hex in the same compile unit. After doing some research I came to the conclusion that probably the only way so solve this is to hide the iterators used in bin_to_hex from the formatter in ranges. 
My change in detail:
When trying to use spdlog/fmt/bin_to_hex.h in the same compile unit as spdlog/fmt/bundled/ranges.h you got a compile error because there was a multiple definitions for iterable classes. This fix renames the begin() and end() getters in dump_info into getBegin()/getEnd() in order to avoid this collision.
Added an example of ranges in example.cpp to show that it actually works (a to_hex example was already there)
What do you think?
All the best
Patrick

Fix usage of ranges and to_hex in the same compile unit

---

include/spdlog/details/os-inl.h

In project i work on, we are warning free, and with our warning policy, we have this warning(even when muting 3rdparty):
`(long int)(local_year - gmt_year) * 365);` in include/details/os-inl.h

Fix warning for gcc, old style cast

---

include/spdlog/async.h
include/spdlog/details/thread_pool-inl.h
include/spdlog/details/thread_pool.h

Hello Gabi,
A while ago, you accepted a pull request https://github.com/gabime/spdlog/pull/208 which was left behind when moving to the thread-pool based async logger.
If this is fine for you, please accept this request and I'll add some lines to the wiki.
Cheers,

Add custom on_stop callback to thread-pool, executed by each thread before joining them.

---

include/spdlog/common.h
include/spdlog/details/os-inl.h

on unix systems `getpid` returns `pid_t` which refers to `signed` type same as `int`

Reduce warnings with pedantic compiler `-Wuseless-cast`

---

include/spdlog/fmt/bin_to_hex.h

`std::span` does not have `const_iterator`. this prevents `to_hex` from
being used with `std::span<>`. to fix this, we provide an explicit
overload.
compare: https://cplusplus.github.io/LWG/issue3320

spdlog: fmt - support `std::span` in `to_hex`

---

include/spdlog/sinks/rotating_file_sink-inl.h

If rotated files on open, `file_helper_` will open an empty file and `current_size_` should be reset to 0.
This PR fixed the bug.

Reset current size if rotated files on open

---

include/spdlog/common.h
include/spdlog/fwd.h
include/spdlog/sinks/ansicolor_sink-inl.h

spdlog::level::level_enum cannot be forward-declared at present, as
the definition does not specify an underlying type.
To allow users to make use of <spdlog/fwd.h> to refer to
level::level_enum without pulling in all of <spdlog/common.h> (which
can be quite costly), specify an underlying type (int) for
level::level_enum, then add a forward-declaration for it to
spdlog/fwd.h.
Note this required explicitly casting level_enum to size_t within ansicolor_sink due to sign-conversion errors:
implicit conversion changes signedness: 'const level::level_enum' to 'std::__1::array::size_type' (aka 'unsigned long') [-Wsign-conversion]
It would appear that an enum with an unspecified underlying type is in
some kind of superposition - it can be treated as both signed _and_
unsigned - using an …

Allow forward-declaration of level_enum

---

include/spdlog/pattern_formatter-inl.h
include/spdlog/pattern_formatter.h

The pattern_formatter class was making unwanted calls to localtime_r or similar functions even when it didn't use the time information.  A flag was added which disables the calls when the pattern formatter is not going to use the information.

Now only getting time if pattern_formatter needs it

---

include/spdlog/sinks/rotating_file_sink-inl.h

Should limit max number of rotating files to 200000, not max size

Limit max number of rotating files to 200000, not max size

---

include/spdlog/pattern_formatter-inl.h

Fix `Wreorder-ctor` warning, as it broke my `-Wall -Wextra -Werror` build.
```
spdlog/pattern_formatter-inl.h:1028:7: error: field 'custom_handlers_' will be initialized after field 'need_localtime_' [-Werror,-Wreorder-ctor]
, custom_handlers_(std::move(custom_user_flags))
^
```
Move the initialization of `need_localtime_(true)` right after `pattern_time_type_` as expected.

pattern_formatter-inl: fix reorder-ctor warning

---

include/spdlog/details/os-inl.h
tests/test_file_helper.cpp

`open()` failure was incorrectly reported as a success under *nix with `SPDLOG_PREVENT_CHILD_FD` enabled, leaving `*fp` untouched.

Fix fopen_s error reporting with PREVENT_CHILD_FD

---

include/spdlog/details/udp_client-windows.h

The original `InetPton` expands to `InetPtonW` when building with UNICODE defined and expects the string parameter to be wchar_t. On the other hand macro `TEXT()` just adds prefix `L` to a string literal (just making it wchar_t literal). The proper way here would be converting `host.c_str()` result from UTF-8(?) into wchar_t (UNICODE) string, but this seems to be an overkill since the host is typically an IP address or a host/domain name. So assuming an ASCII input should be reasonably safe.

Fixed compiler error when building on Windows with #define UNICODE

---

include/spdlog/sinks/systemd_sink.h

Add option to enable formatting of systemd sink

---

include/spdlog/common.h

Just making file_event_handlers an aggregate to allow designated initialization

Make file_event_handlers an aggregate

---

src/async.cpp

see the issue: https://github.com/gabime/spdlog/issues/2332

[issues/2332]clean code, clean up the warning

---

include/spdlog/common.h
include/spdlog/details/fmt_helper.h
include/spdlog/details/os-inl.h
include/spdlog/logger.h
include/spdlog/sinks/msvc_sink.h
include/spdlog/sinks/ringbuffer_sink.h
tests/includes.h
tests/test_daily_logger.cpp
tests/test_errors.cpp
tests/test_fmt_helper.cpp
tests/test_pattern_formatter.cpp

Drive-by: reduce the amount of occurences of `#ifdef SPDLOG_USE_STD_FORMAT`

Switch to vformat_to

---

include/spdlog/pattern_formatter-inl.h
include/spdlog/pattern_formatter.h
tests/test_pattern_formatter.cpp

If user wants to use the pattern with no builtin flags related to time, but custom formatter that needs time information, there is no way to make pattern_formatter pass the updated `const std::tm&` to `format()` of custom formatter. This PR allows user to override `need_localtime` so that custom formatter can utilize cached_tm with the pattern not enabling `need_localtime` by default.

Allow overriding need_localtime for custom formatter

---

include/spdlog/sinks/android_sink.h

Reverting unintended merge into master in #2352
This reverts commit c6d048747419e886fac830d4cba9ad14e3a41461, reversing
changes made to a51b4856377a71f81b6d74b9af459305c4c644f8.

Revert "Merge pull request #2352 from tiolan/topic/android_buffer"

---

example/example.cpp
include/spdlog/common.h
include/spdlog/fmt/bin_to_hex.h

@gabime  I'm unable to test that the changes for `__has_include` in bin_to_hex.h work for @aengusjiang, but the approach I've followed matches the recommended pattern in the [gcc documentation for __has_include](https://gcc.gnu.org/onlinedocs/cpp/_005f_005fhas_005finclude.html).
I have tested the rest of the changes on my machine with gcc version `gcc (Ubuntu 5.5.0-12ubuntu1~14.04) 5.5.0 20171010`. I get the overloaded formatter used as seen in the output from the example program:
> [2022-05-11 18:22:25.008] [info] user defined type: [my_type i=14]
The problem seems to be caused by this clause in the [namespace specification](https://en.cppreference.com/w/cpp/language/namespace) (emphasis added):
>To reopen an existing namespace (formally, to be an extension-namespace-definition), the …

C++14 build fixes for older gcc #2333

---

include/spdlog/details/file_helper-inl.h
include/spdlog/details/file_helper.h
include/spdlog/details/os-inl.h
include/spdlog/details/os.h

Since file_helper already works well for managing file sinks and generally can be reused, it seems reasonable to me to implement fsync there which is required in some cases.
This adds `sync()` method to file_helper. It doesn't affect existing sinks and doesn't touch public interfaces.

Add sync to file_helper
