include/spdlog/async_logger.h
include/spdlog/details/async_log_helper.h
include/spdlog/details/async_logger_impl.h
include/spdlog/details/registry.h
include/spdlog/details/spdlog_impl.h
include/spdlog/spdlog.h

feature allowing to run certain code in the beginning of the worker thread.
one can use it to set thread priority, affinity mask, etc.

worker warmup callback

---

include/spdlog/spdlog.h

issue #65: added macroses like SPDLOG_TRACE but with no force

---

include/spdlog/sinks/file_sinks.h

adds missing flush override to simple_file_sink

---

include/spdlog/async_logger.h
include/spdlog/details/async_log_helper.h
include/spdlog/details/async_logger_impl.h
include/spdlog/details/registry.h
include/spdlog/details/spdlog_impl.h
include/spdlog/spdlog.h

how about this? please share your thoughts

async auto flush

---

include/spdlog/details/pattern_formatter_impl.h

First time I'm doing this on Github, I hope I've not messed it up :)
It looks like some builds are failing, but I think unrelated to the change - the error is "The command "which $CXX" failed and exited with 1 during ."

fixed issue 115 Nanosecond resolution timestamps

---

include/spdlog/details/os.h

Fix Android build for API < 21.

Fix Android build

---

include/spdlog/details/os.h
include/spdlog/tweakme.h

I added new tweak which add ability to use CLOCK_MONOTONIC. It's much faster than CLOCK_REALTIME and more accurate than CLOCK_REALTIME_CORSE.

Added CLOCK_MONOTONIC trick

---

include/spdlog/details/os.h

This code:
```c++
if (!rv)
return -1;
```
compares `rv` to `TIME_ZONE_ID_UNKNOWN == 0`
`TIME_ZONE_ID_UNKNOWN` means
> "Daylight saving time is not used in the current time zone, because there are no transition dates or automatic adjustment for daylight saving time is disabled." ([see Microsoft documentation](https://msdn.microsoft.com/en-us/library/windows/desktop/ms724421(v=vs.85).aspx))
so if the time zone doesn't have DST (like Europe/Moscow UTC+03:00) the function returns `-1`.
`Get[Dynamic]TimeZoneInformation` returns `TIME_ZONE_ID_INVALID` if it fails so comparing `rv` to it is the correct way to detect an error.
Also (not in the pull request as would violate the function's interface) it would be logical to throw an exception instead of returning `-1`:
```c++
throw …
```

Fixed issues with time zone UTC offset and daylight saving offset on Windows

---

.gitignore
CMakeLists.txt
cmake/spdlog.pc.in

For [pkg-config](https://www.freedesktop.org/wiki/Software/pkg-config).

Generate & Install pkg-config File

---

include/spdlog/sinks/file_sinks.h
tests/file_log.cpp

Standard sinks::daily_file_sink uses hardcoded way of filename calculation. If an user don't like names in form base_YYYY-MM-DD_hh_mm.ext it has to write its own daily_file_sink implementation. But this implementation will have only one difference -- body of calc_filename() method. All other code will be a copy-paste from original daily_file_sink class. I think it is not good.
I have added a possibility to customize filename calculation via additional template parameter for sinks::daily_file_sink class. This parameter has default value. It means that there can be a good compatibility with old code.
With this approach an user can define its own daily_file_name_calculator class with just one static method and use it as a parameter to daily_file_sink class.
I have also extented …

daily_file_sink with custom file name calculator

---

include/spdlog/details/spdlog_impl.h
include/spdlog/spdlog.h

Create a logger with a single sink

---

include/spdlog/details/spdlog_impl.h
include/spdlog/sinks/file_sinks.h
include/spdlog/spdlog.h

Added the ability to truncate the basic file logger. [Discussion](https://github.com/gabime/spdlog/issues/264).

Added the ability to truncate the basic file logger.

---

include/spdlog/details/logger_impl.h
include/spdlog/logger.h

Don't mean to step on the other guys toes who did this, but I noticed he never made the requested changes. Didn't want my deps to be out of sync with the master.

Exposed logger sinks.

---

include/spdlog/sinks/wincolor_sink.h

This should fix issue #321 (just reported).

Fix compilation errors in "wincolor_sink.h"

---

example/example.cpp
include/spdlog/details/spdlog_impl.h
include/spdlog/sinks/file_sinks.h
include/spdlog/spdlog.h
tests/file_log.cpp

Signed-off-by: Ľubomír Carik <Lubomir.Carik@gmail.com>

Don't hardcode '.txt.' log file name suffix (resolve #333)

---

include/spdlog/sinks/android_sink.h

in some cases subsequent calls to __android_log_write() may result with -EAGAIN error code.
in such cases spdlog will sleep and try again for number of times defined in tweakme.h
default behavior not changed
issue: #424

android sink - add retry mechanism

---

include/spdlog/details/os.h

Fix OSX builds of details/os.h

---

include/spdlog/async_logger.h
include/spdlog/common.h
include/spdlog/details/async_log_helper.h
include/spdlog/details/async_logger_impl.h
include/spdlog/details/file_helper.h
include/spdlog/details/log_msg.h
include/spdlog/details/logger_impl.h
include/spdlog/details/mpmc_bounded_q.h
include/spdlog/details/os.h
include/spdlog/details/pattern_formatter_impl.h
include/spdlog/details/registry.h
include/spdlog/details/spdlog_impl.h
include/spdlog/fmt/fmt.h
include/spdlog/fmt/ostr.h
include/spdlog/formatter.h
include/spdlog/logger.h
include/spdlog/sinks/base_sink.h
include/spdlog/sinks/file_sinks.h
include/spdlog/sinks/sink.h
include/spdlog/sinks/stdout_sinks.h
include/spdlog/sinks/wincolor_sink.h
include/spdlog/spdlog.h

Fixed issues 449

---

README.md
example/example.cpp
include/spdlog/details/logger_impl.h
include/spdlog/logger.h
include/spdlog/spdlog.h
tests/cond_logging.cpp
tests/tests.vcxproj
tests/tests.vcxproj.filters

Please check this pull request.
I have added the [conditional logging feature](https://github.com/gabime/spdlog/issues/388).

conditional logging

---

include/spdlog/sinks/ansicolor_sink.h

It is now possible again to set the color in the ansicolor_sink with set_color. #464

Add set_color to ansicolor_sink

---

example/example.cpp
include/spdlog/details/async_logger_impl.h
include/spdlog/details/logger_impl.h
include/spdlog/details/pattern_formatter_impl.h
include/spdlog/details/registry.h
include/spdlog/logger.h
include/spdlog/sinks/ansicolor_sink.h
include/spdlog/sinks/base_sink.h
include/spdlog/sinks/dist_sink.h
include/spdlog/sinks/file_sinks.h
include/spdlog/sinks/msvc_sink.h
tests/cond_logging.cpp

PR aims to solve the issue #467 
But CI [run](https://travis-ci.org/p-alik/spdlog/jobs/248258538#L453) failed on 
```bash
cd $CHECKOUT_PATH/tests; make rebuild; ./tests
make: *** No rule to make target `rebuild'.  Stop.
/home/travis/.travis/job_stages: line 54: ./tests: No such file or directory
```
Is it my blunder?

code formatting (astyle and dos2unix)

---

include/spdlog/spdlog.h

Added TRACE/DEBUG_IF macro definitions when TRACE/DEBUG_ON aren't defined

---

README.md

https://packages.gentoo.org/packages/dev-libs/spdlog

readme: Add Gentoo package name

---

appveyor.yml

Builds repo for:
- MinGW 32bit
- Visual Studio 2015 32bit
- Visual Studio 2015 64bit
Signed-off-by: Remigiusz Kołłątaj <remigiusz.kollataj@gmail.com>

Adding additional build environments for AppVeyor

---

include/spdlog/sinks/msvc_sink.h
include/spdlog/sinks/windebug_sink.h

accept msvc_sink on all compilers, add name windebug_sink (fixes #554)

---

tests/errors.cpp

Signed-off-by: Ľubomír Carik <Lubomir.Carik@anritsu.com>

Solve compiler warning in tests

---

include/spdlog/details/file_helper.h
tests/file_helper.cpp

See https://github.com/gabime/spdlog/issues/589

fix split_by_extenstion parse error extenstion

---

include/spdlog/details/async_log_helper.h
include/spdlog/details/file_helper.h
include/spdlog/details/os.h
include/spdlog/sinks/android_sink.h

Fixes #609
@gabime Please give it a proper review... I'm not too comfortable in C++ to make such changes.

Use Sleep in Windows instead of sleep_for

---

bench/boost-bench-mt.cpp
bench/easylogging-bench-async.cpp
bench/easylogging-bench-mt.cpp
bench/easylogging-bench.cpp
bench/g3log-async.cpp
bench/glog-bench.cpp
bench/log4cplus-bench-mt.cpp
bench/log4cplus-bench.cpp
bench/log4cpp-bench-mt.cpp
bench/log4cpp-bench.cpp
bench/p7-bench-mt.cpp
bench/p7-bench.cpp
bench/spdlog-async.cpp
bench/spdlog-bench-mt.cpp
example/example.cpp
include/spdlog/details/log_msg.h
include/spdlog/details/os.h
include/spdlog/details/pattern_formatter_impl.h
include/spdlog/sinks/ansicolor_sink.h
include/spdlog/sinks/wincolor_sink.h
tests/test_pattern_formatter.cpp

Support for custom color ranges like  %^text%$ in formatter

Color formatting

---

include/spdlog/sinks/android_sink.h

fix bug in android_sink.h

---

include/spdlog/sinks/android_sink.h

Namespace fix  for the issue 785

---

tests/registry.cpp

Fix registry test

---

include/spdlog/details/fmt_helper.h

Cleanup header file: remove log_msg.h include from fmt_helper.h

---

include/spdlog/details/async_logger_impl.h
include/spdlog/details/thread_pool.h

There is more clearly than using the log_msg&&

change the log_msg&& to log_msg&

---

README.md

Hello.
With this PR I just fix very small typo in the Android example.

Fix typo in Android example

---

include/spdlog/details/fmt_helper.h
include/spdlog/details/pattern_formatter.h

Fix osx build

---

include/spdlog/details/fmt_helper.h

Merged my previous PR a little too fast.

Fix template error

---

include/spdlog/details/file_helper.h
include/spdlog/sinks/daily_file_sink.h
include/spdlog/sinks/rotating_file_sink.h
tests/test_file_helper.cpp

Fix typo in file_helper.h

---

include/spdlog/sinks/basic_file_sink.h
include/spdlog/sinks/daily_file_sink.h
include/spdlog/sinks/rotating_file_sink.h

Add method to filesinks to return filename

---

include/spdlog/spdlog.h

Related #1025
Add public API `spdlog::initialize_logger` for create loggers manually.

Add spdlog::initialize_logger

---

include/spdlog/common.h
include/spdlog/details/os-inl.h
include/spdlog/details/os.h
include/spdlog/logger.h

Fix deprecation warnings in filename_to_str and improve performance of wbuf_to_utf8buf

---

include/spdlog/sinks/daily_file_sink.h

Related https://github.com/gabime/spdlog/pull/1128.

Fix one more `msg.time` in daily_file_sink.

---

include/spdlog/details/os-inl.h

Example of this warning on [Travis builds](https://travis-ci.com/AMS21/AGE/jobs/226451509#L2532)

Fix Wundef in os-inl.h

---

include/spdlog/details/os-inl.h

This will fix errors relating to -Werror usage.

Remove unused variable

---

meson.build

Fixes https://github.com/gabime/spdlog/issues/1336

Set version for shared library

---

CMakeLists.txt

See also https://gitlab.kitware.com/cmake/cmake/merge_requests/4300

CMakeLists.txt: put GNUInstallDirs after set project language

---

example/CMakeLists.txt
tests/CMakeLists.txt

Enable running the tests against an installed copy of spdlog

---

include/spdlog/sinks/tcp_sink.h

Adding SOCK_CLOEXEC to socket
Fixing bug in sink_it_ (bytes_sent not added to buffer)
If requested I would also add some code to better handle the connect.
When behind a proxy and the tcp packed get swallowed the default connect timeout in
most Implementations is around 2 minutes.
I would add some code to reduce this timeout, maybe also as parameter to constructor.

Handling SPDLOG_PREVENT_CHILD_FD in tcp_sink

---

include/spdlog/sinks/daily_file_sink.h
include/spdlog/sinks/rotating_file_sink-inl.h
include/spdlog/sinks/rotating_file_sink.h

Avoid references to race data filename

---

README.md

Add example to FMT_STRING in README

---

include/spdlog/details/os-inl.h

Fix a build issue when SPDLOG_PREVENT_CHILD_FD is defined

---

include/spdlog/logger.h
include/spdlog/pattern_formatter.h
include/spdlog/spdlog.h

Perfect forwarding for arguments

---

include/spdlog/sinks/hourly_file_sink.h

I added an hourly file sink. It would be nice if it could be included in the repository. In my opinion this is a missing feature in an otherwise great library! The daily_file_sink is edited to create an hourly file sink.

Add Hourly file sink

---

include/spdlog/common-inl.h
include/spdlog/common.h
include/spdlog/pattern_formatter-inl.h

add constexpr to SPDLOG_LEVEL_NAMES declaration

---

bench/formatter-bench.cpp

Avoid relying on function name decay mechanics

---

example/example.cpp

Minor typo

---

CMakeLists.txt

Add support for CMake policy CMP0077

---

example/example.cpp
include/spdlog/fmt/bin_to_hex.h
include/spdlog/logger.h

Check `FMT_STRING` format strings at compile time

Check args on formatting

---

include/spdlog/sinks/qt_sinks.h

Fixed qt_sinks ctor

---

README.md

https://travis-ci.com/gabime/spdlog (404's) → https://app.travis-ci.com/gabime/spdlog
https://travis-ci.com/gabime/spdlog.svg?branch=v1.x → https://app.travis-ci.com/gabime/spdlog.svg?branch=v1.x (Result from clicking Status Image url builder)

Update to latest Travis CI Build Status

---

include/spdlog/details/udp_client-windows.h
include/spdlog/details/udp_client.h

[inet_aton()](https://linux.die.net/man/3/inet_aton), [InetPton()](https://docs.microsoft.com/en-us/windows/win32/api/ws2tcpip/nf-ws2tcpip-inet_pton#return-value) return codes

Unhandled errors

---

include/spdlog/common.h

This was slightly annoying me so I fixed it.

Remove extraneous semicolon

---

include/spdlog/pattern_formatter.h

On Line 83 someone probably misclicked tab just removed that tab

removed unneeded spaces

---

include/spdlog/pattern_formatter-inl.h

Fix #2201  
Add ScopedPadder if the source information is empty while formatting source information fields

Fix issue #2201

---

include/spdlog/sinks/systemd_sink.h

Add optional "ident" argument to systemd sink constructor

---

include/spdlog/sinks/android_sink.h

Please consider this untested change WIP and a basis for discussion.
This would allow setting the Android log buffer to be used from outside.
Would something like this have a change to be merged?
The usage of a macro is not really nice, but simple and does not break the API.
Another approach could be to again template `android_sink` and provide a default template argument for not breaking the API.
Would need to see how this is compatible with C++11.
What are your thoughts?

Allow modifying the used Android buffer

---

include/spdlog/sinks/android_sink.h

Following up on #2352, but merging into v1.x

V1: Allow modifying the used Android buffer

---

tests/test_misc.cpp

fix clone async test
